### PR TITLE
UX menu redesign

### PR DESCRIPTION
**Pull request by prakashsvmx**
UX menu redesign

UX Spec:
https://xd.adobe.com/view/24e0e3b4-8947-46fb-8e56-b8f88de319b7-71b3/screen/6e2be7e7-fd25-4d74-a29e-dd5242226ac0/

<summary> How does it look: <summary>

<details>

image

image

image

</details>

### CODE REVIEW

**Comment by prakashsvmx** [comment]
@dvaldivia  Requesting feedback on the missing items ( Service accounts, Tiers,  Endpoints etc..)  placement.

Also for the new menu items, should we skip rendering until there is a real screen or can we implement "under construction" or "coming soon" page?

@oscarocastellanos  

meanwhile i will update the ui tests.

**Comment by oscarocastellanos** [comment]
@prakashsvmx We had a design for when a module o section is not available. I'm thinking we can implement that one on these. This is the XD link for the design I made:

https://xd.adobe.com/view/1ad45f78-016d-4899-adb9-7179b33704ff-4f87/

Let me know what you think. Thanks!

**Comment by prakashsvmx** [comment]
@kaankabalak  shall we update the tests to use the urls from the menu list. ( `IAM_PAGES.XXX` ?). instead of hardcoding?

Also now the menus are collapsible so we may need to update accordingly as well.

I shall update if it is not already in progress.

**Review by oscarocastellanos — APPROVED** [review]

**Comment by dvaldivia** [comment]
Tested. LGTM.
Screen Shot 2022-01-20 at 8 10 18 AM

**Review by dvaldivia — APPROVED** [review]

**Comment by kaankabalak** [comment]
> @kaankabalak shall we update the tests to use the urls from the menu list. ( `IAM_PAGES.XXX` ?). instead of hardcoding?
> 
> Also now the menus are collapsible so we may need to update accordingly as well.
> 
> I shall update if it is not already in progress.

Yes, you can update the tests 👍

**Comment by dvaldivia** [comment]
@kaankabalak @prakashsvmx let's update those on a separate PR

**Pull request merged**
