### PR TITLE
Protocol Logos for Add Tenant - Identity Provider 

### PR DESCRIPTION
**Pull request by jinapurapu**
Screenshot from 2022-08-03 14-39-49
Screenshot from 2022-08-03 14-40-18

closes https://github.com/miniohq/engineering/issues/711

### CODE REVIEW

**Comment by pjuarezd** [comment]
Is there plans to add the icons in the edit tenant page? or is this not in the scope?

Screen Shot 2022-08-01 at 9 34 25 AM

**Review by bexsoft — CHANGES_REQUESTED** [review]
Could it be possible to add the icons next to the button label, please?

Perhaps something like this:

Screen Shot 2022-08-01 at 18 08 11

**Comment by dvaldivia** [comment]
@bexsoft @jinapurapu we would need to implement a new parameter for the RadioGroup component to layout the options in column format to allow for the spacing to go this way

**Review by pjuarezd — DISMISSED** [review]

**Review by reivaj05 — DISMISSED** [review]

**Review by dvaldivia — CHANGES_REQUESTED** [review]
There's a little misaligned of the radio buttons, the icon and the text. I propose we size down the icons to `16px` and fix the line height to have them show aligned horizontally 

idp alignment

**Review by dvaldivia — APPROVED** [review]
Looks awesome
Screen Shot 2022-08-03 at 2 38 00 PM

**Review by bexsoft — APPROVED** [review]
LGTM

**Review by bexsoft — DISMISSED** [review]
Please prettify the files

**Review by prakashsvmx — APPROVED** [review]
Tested. Looks good to me.

**Review by dvaldivia — APPROVED** [review]

**Pull request merged**
