### PR TITLE
Fixed broken oauth2 login for operator

### PR DESCRIPTION
**Pull request by Alevsk**
This PR includes many fixes and refactors for oauth2 authentication and
login endpoints, ie:

- Invalid login returns `403` instead of `500` error
- Removed the session token from console/operator `user credentials
  login`, `oauth flow login` and `change-password` api responses
- Removed session token from localStorage
- Added styles for oauth_callback page and display more descriptive
  errors for debugging
- Success logins returns `204` instead of `200`
- Removed unused swagger apis and code from both, operator and console
  projects
- Operator `Oauth2` login flow was not validating anything, now it does

# Error on `oauth_callback` page before

Screen Shot 2021-11-10 at 18 43 32

# Error on `oauth_callback` page now

Screen Shot 2021-11-10 at 18 28 02

Signed-off-by: Lenin Alevski <alevsk.8772@gmail.com>

### CODE REVIEW

**Comment by harshavardhana** [comment]
Some integration tests are failing with MinIO @Alevsk

**Comment by Alevsk** [comment]
> Some integration tests are failing with MinIO @Alevsk 

These tests are failings on master ; I'll investigated why they are failing

**Comment by harshavardhana** [comment]
> These tests are failing on master already, I'll investigated why they are failing

No they are not @Alevsk https://github.com/minio/console/runs/4174881009?check_suite_focus=true - I ran them a few times already.

**Comment by harshavardhana** [comment]
> No they are not @Alevsk https://github.com/minio/console/runs/4174881009?check_suite_focus=true - I ran them a few times already.

You can test locally `make test-integration`

**Comment by Alevsk** [comment]
> > No they are not @Alevsk https://github.com/minio/console/runs/4174881009?check_suite_focus=true - I ran them a few times already.
> 
> You can test locally `make test-integration`

I'm looking at this right now

**Review by harshavardhana — APPROVED** [review]

**Review by dvaldivia — APPROVED** [review]

**Pull request merged**
