### PR TITLE
Release v1.7.4

### PR DESCRIPTION
**Pull request by bexsoft**

### CODE REVIEW

**Review by bayasdev — APPROVED** [review]

**Review by reivaj05 — APPROVED** [review]

**Comment by donatello** [comment]
Do we merge with the CI failure?

**Comment by bexsoft** [comment]
> Do we merge with the CI failure?

This PDF issue is not a real failure, PDF is rendered correctly in the UI Locally I see an error related to pdf worker library required for this and testcafe. This needs further investigation

**Review by bayasdev — APPROVED** [review]

**Review by cesnietor — COMMENTED** [review]
Please add Changelog.md

**Review by ramondeklein — COMMENTED** [review]
@bexsoft Did you regenerate the files after rebasing to the latest `master`? When I run `make release`, then all generated files are different but that may be caused due to different versions. I do think the `build` folder should be identical and not depend on whoever runs `make release`.

For that reason, I am always a fan of letting the CI/CD build the final output instead. Then it's consistent.

**Comment by bexsoft** [comment]
> @bexsoft Did you regenerate the files after rebasing to the latest `master`? When I run `make release`, then all generated files are different but that may be caused due to different versions. I do think the `build` folder should be identical and not depend on whoever runs `make release`.
> 
> For that reason, I am always a fan of letting the CI/CD build the final output instead. Then it's consistent.

Yes, @ramondeklein, all files are updated with the latest master change. we use a release script to generate these files, maybe could be related

**Review by ramondeklein — APPROVED** [review]
WIth the removal of functionality, this isn't a patch. It should at least be named v1.8.0. But I don't think version number is actually being used -outside MinIO-, so I guess it's fine...

**Comment by feorlen** [comment]
@bexsoft corresponding docs ready to merge

**Review by cesnietor — APPROVED** [review]

**Review by reivaj05 — APPROVED** [review]

**Review by bayasdev — APPROVED** [review]

**Pull request merged**
