### PR TITLE
Removing unused parameters

### PR DESCRIPTION
**Pull request by cniackz**
Fixes miniohq/engineering#453

To remove unused parameters from `List Buckets` end point at Console API

### CODE REVIEW

**Review by adfost — DISMISSED** [review]

**Review by dvaldivia — CHANGES_REQUESTED** [review]
Please check the swagger version, with `v0.28.0` a lot of files get changed

```
➜ git status
On branch remove-limit
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   models/bucket_access.go
	modified:   models/bucket_encryption_type.go
	modified:   models/nofitication_service.go
	modified:   models/notification_event_type.go
	modified:   models/object_legal_hold_status.go
	modified:   models/object_retention_mode.go
	modified:   models/object_retention_unit.go
	modified:   models/policy_entity.go
	modified:   models/profiler_type.go
```

**Review by dvaldivia — DISMISSED** [review]
We will move to `v0.29.0`

**Review by jinapurapu — DISMISSED** [review]

**Comment by cniackz** [comment]
Daniel, I ran two commands inside this branch on this PR.
```
make swagger-gen
go mod tidy 
```
And there wasn't change in `go.mod` nor in `go.sum` like the other time I
modified these files in: https://github.com/minio/console/pull/1393
I assume that dependencies are good to go. Nevertheless, I observe that we
don't have the latest of some of those dependencies, example:
```
github.com/go-openapi/errors v0.20.1 <----- this is an old version, should I up date it?
```

**Comment by cniackz** [comment]
Ok Daniel, I retrieved the latest versions from the repo's tags for `go-openapi` and `swag` and modified the `go.mod` and the `go.sum` accordingly.

**Review by dvaldivia — APPROVED** [review]

**Review by bexsoft — APPROVED** [review]

**Pull request merged**
