### PR TITLE
add encoded filename as part of upload url

### PR DESCRIPTION
**Pull request by prakashsvmx**
pass encoded file name also as part of the url.
- Upload a single/multiole files
- Upload a folder
- Drag and drop
- upload under a prefix

the file name is part of `prefix=`  parameter. parameter added for tooling support.

e.g:
```
http://localhost:5005/api/v1/buckets/test-bucket/objects/upload?prefix=dGVzdC1wcmVmaXgvMS5kb2M=
http://localhost:5005/api/v1/buckets/test-bucket/objects/upload?prefix=MS5wbmc=

```

### CODE REVIEW

**Review by dvaldivia — APPROVED** [review]
LGTM.

**Comment by cesnietor** [comment]
@prakashsvmx  can we make it part of the same parameter `prefix`? all other apis have both, the path and the object in there.

**Review by cesnietor — CHANGES_REQUESTED** [review]
please see comments

**Comment by prakashsvmx** [comment]
@cesnietor if `prefix` is passed, backend makes it as a folder. So I isolated it (and added code comments) to make it non breaking change.

**Comment by cesnietor** [comment]
> @cesnietor if `prefix` is passed, backend makes it as a folder. So I isolated it (and added code comments) to make it non breaking change.

yes, in this case we would need to change the backend a bit. that's fine.
Instead of using prefix + file name it would have to be whole prefix.
```
_, err = client.putObject(ctx, params.BucketName, path.Join(prefix, path.Clean(p.FileName())), p, size, minio.PutObjectOptions{
			ContentType:      contentType,
			DisableMultipart: true, // Do not upload as multipart stream for console uploader.
		})
```
to :
```
_, err = client.putObject(ctx, params.BucketName, prefix,...
```

**Comment by prakashsvmx** [comment]
Thank you @cesnietor . I will check and update.

**Review by cesnietor — DISMISSED** [review]
Tested LGTM, thanks @prakashsvmx !

**Comment by cesnietor** [comment]
I tried uploading a file with the following objects inside and some uploads failed
Screenshot 2023-12-04 at 11 07 41 AM
Screenshot 2023-12-04 at 11 07 18 AM

Requests failing:
`http://localhost:5005/api/v1/buckets/bucket1/objects/upload?prefix=L2ZvbGRlcjEvZm9sZGVyMy8=cGRmd2l0aEFsZXJ0LnBkZg==
`
and
`http://localhost:5005/api/v1/buckets/bucket1/objects/upload?prefix=L2ZvbGRlcjEvMi8=cGRmd2l0aEFsZXJ0LnBkZg==
`

**Comment by prakashsvmx** [comment]
@cesnietor , Thank you, i have now updated , and also the tests related to back end changes.

**Comment by allanrogerr** [comment]
@prakashsvmx Please check Vulnerability #1: GO-2023-2382

**Review by allanrogerr — APPROVED** [review]
Tested

**Pull request merged**
