### PR TITLE
Fix config parsing using updated method

### PR DESCRIPTION
**Pull request by donatello**
- The config parsing client-side logic is updated in madmin-go

### CODE REVIEW

**Comment by donatello** [comment]
Needs https://github.com/minio/madmin-go/pull/115

**Comment by donatello** [comment]
Should resolve https://github.com/minio/console/issues/2247

**Comment by donatello** [comment]
Also needs https://github.com/minio/mc/pull/4212

**Review by harshavardhana — APPROVED** [review]
LGTM & tested

**Comment by donatello** [comment]
Needs mc bump up

**Comment by donatello** [comment]
Needs a look at the ilm changes related to breakage from mc bump up.

**Comment by donatello** [comment]
Config API test failure is addressed via https://github.com/minio/minio/pull/15559

**Comment by donatello** [comment]
Due to the way ILM client side edit logic has changed (now requires a lifecycle rule ID), this will likely need fixes in the UI for ILM edit operation  -> https://github.com/minio/console/pull/2251/files#diff-6dc21714a8dceee803f2cc29a3ab2f4d29cc3433265875585bae1d0af4925631

CC: @Alevsk @bexsoft

**Comment by donatello** [comment]
Except for https://github.com/minio/console/runs/7924897416?check_suite_focus=true - the others are expected failures and should get resolved once minio is updated with the new console version. For this failure, I am still trying to understand the cause. @Alevsk @bexsoft @harshavardhana

**Comment by donatello** [comment]
Confirmed that remaining failure is not related to this change. We should be good to merge this one.

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
Can we get a console release here today? so that we can include this with MinIO release? 

// cc @cniackz @bexsoft @Alevsk @dvaldivia

**Review by bexsoft — APPROVED** [review]
LGTM, Found another issue with settings page not related to this change. Will send a new PR for this.

**Comment by harshavardhana** [comment]
👍🏽

**Pull request merged**
