### PR TITLE
Bucket list actions menu redesign

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

Added redesign for buckets list menu actions & removes single action buttons from list

## How does it look?
Screen Shot 2022-01-26 at 16 54 07
Screen Shot 2022-01-26 at 16 53 47
Screen Shot 2022-01-26 at 16 53 36

### CODE REVIEW

**Review by dvaldivia — CHANGES_REQUESTED** [review]
the dimensions and font size are a little off, but other than that it looks great, can we match the `height 40` and `fontSize: 14` ?
Screen Shot 2022-01-26 at 3 42 28 PM

**Comment by dvaldivia** [comment]
Screen Shot 2022-01-26 at 3 49 23 PM
I cannot create a new path (folder) on a prefix which I should.

Steps to repro:

1.- create bucket called `mycache` with a prefix `mysoftware` inside and place a file in `mycache/mysoftware`
2.- create a user with the following policy
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": ["s3:ListBucket","s3:GetBucketLocation"],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::mycache"]
    },
    {
      "Action": ["s3:ListBucket","s3:GetObject"],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::mycache/*"]
    },
    {
      "Action": [
        "s3:ListBucket",
        "s3:GetObject",
        "s3:PutObject",
        "s3:DeleteObject"
      ],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::mycache/mysoftware/*"]
    }
  ]
}
```
3.- go to `mycache > Browse > mysoftware`
4.- I should be allowed to create a subfolder

**Comment by bexsoft** [comment]
> the dimensions and font size are a little off, but other than that it looks great, can we match the `height 40` and `fontSize: 14` and icon sizes ? Screen Shot 2022-01-26 at 3 42 28 PM

Solved:
Screen Shot 2022-01-26 at 22 15 14

**Comment by bexsoft** [comment]
> Screen Shot 2022-01-26 at 3 49 23 PM
> 
> I cannot create a new path (folder) on a prefix which I should.
> Steps to repro:
> 
> 1.- create bucket called `mycache` with a prefix `mysoftware` inside and place a file in `mycache/mysoftware` 2.- create a user with the following policy
> 
> ```json
> {
>   "Version": "2012-10-17",
>   "Statement": [
>     {
>       "Action": ["s3:ListBucket","s3:GetBucketLocation"],
>       "Effect": "Allow",
>       "Resource": ["arn:aws:s3:::mycache"]
>     },
>     {
>       "Action": ["s3:ListBucket","s3:GetObject"],
>       "Effect": "Allow",
>       "Resource": ["arn:aws:s3:::mycache/*"]
>     },
>     {
>       "Action": [
>         "s3:ListBucket",
>         "s3:GetObject",
>         "s3:PutObject",
>         "s3:DeleteObject"
>       ],
>       "Effect": "Allow",
>       "Resource": ["arn:aws:s3:::mycache/mysoftware/*"]
>     }
>   ]
> }
> ```
> 
> 3.- go to `mycache > Browse > mysoftware` 4.- I should be allowed to create a subfolder

This issue seems to be already present as hasPermissions function is returning me false in master too. This is not related to this PR, and will be fixed in another one

**Review by prakashsvmx — APPROVED** [review]
Tested. 
- Un Versioned Bucket/Objects
- Versioned Bucket/Objects

Changes look good to me.

**Review by dvaldivia — APPROVED** [review]

**Pull request merged**
