### PR TITLE
Fix Subpath behavior

### PR DESCRIPTION
**Pull request by dvaldivia**
Fixes subpath behavior for `Console`

# How to Test this PR

## Vanilla nginx

Assuming we are exposing the console under `http://localhost:8000/console/subpath/`

1. Make assets via `make assets` and build MinIO with this branch of console
2. Start MinIO for a given Subpath
```bash
CI=true;MINIO_BROWSER_REDIRECT_URL=http://localhost:8000/console/subpath/;MINIO_SERVER_URL=http://localhost:9000 minio --console-address ":9090"
```
3. Start `nginx` with the following configuraiton
```
events { worker_connections 1024; }

http {

server {
    listen 8000;

    location /console/subpath/ {
        rewrite   ^/console/subpath/(.*) /$1 break;
        proxy_pass http://localhost:9090;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # This allows WebSocket connections
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

}
```
with the command
```
nginx -c /PATH/TO/nginx.conf -g "daemon off;"
```
4. Visit http://localhost:8000/console/subpath/ on a browser
Screenshot 2023-05-17 at 12 10 45 PM

## In Kubernetes with nginx ingress

1. Create a Tenant with the the address for console under a subpath:
```yaml
  features:
    domains:
      console: https://ns-1.minio-x1/console/subpath/
      minio:
        - https://ns-1.minio-x1
```
Full Tenant Example:
```yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: subpath-tenant
  namespace: ns-1
spec:
  configuration:
    name: subpath-tenant-env-configuration
  credsSecret:
    name: subpath-tenant-secret
  exposeServices:
    console: true
    minio: true
  features:
    domains:
      console: https://ns-1.minio-x1/console/subpath/
      minio:
        - https://ns-1.minio-x1
  image: miniodev/minio:subpath
  imagePullSecret: { }
  mountPath: /export
  pools:
    - affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/tenant
                    operator: In
                    values:
                      - subpath-tenant
                  - key: v1.min.io/pool
                    operator: In
                    values:
                      - pool-0
              topologyKey: kubernetes.io/hostname
      name: pool-0
      resources: { }
      runtimeClassName: ""
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "68719476736"
          storageClassName: standard
      volumesPerServer: 4
  requestAutoCert: true
  users:
    - name: subpath-tenant-user-0
```

Screenshot 2023-05-17 at 12 13 23 PM

2. Create an ingress controller with the subpath
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ns-1-ingress
  namespace: ns-1
  labels:
    app: console
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 5120g
spec:
  rules:
    - host: ns-1.minio-x1
      http:
        paths:
          - pathType: Prefix
            path: "/console/subpath/(.*)"
            backend:
              service:
                name: subpath-tenant-console
                port:
                  number: 9443
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: minio
                port:
                  number: 443
```

3. visit https://ns-1.minio-x1/console/subpath/
Screenshot 2023-05-17 at 12 14 58 PM

In all cases:
- Assets will load
- API calls will work
- Websockets will work

Fixes https://github.com/minio/console/issues/1908
Fixes https://github.com/minio/console/issues/2045
Fixes https://github.com/minio/console/issues/2149
Fixes https://github.com/minio/console/issues/2188
Fixes https://github.com/minio/console/issues/2483
Fixes https://github.com/minio/console/issues/2766
Fixes https://github.com/minio/console/issues/2774
Fixes https://github.com/minio/console/issues/2775

### CODE REVIEW

**Comment by allanrogerr** [comment]
Vanilla nginx
Im facing this `open build/index.html: file does not exist`. Any tips?

**Review by reivaj05 — APPROVED** [review]

**Review by bexsoft — CHANGES_REQUESTED** [review]
There is an issue while trying to create a bucket. API returns 404 while fetching API. 
Tested with provided steps
Screenshot 2023-05-18 at 11 58 16
Screenshot 2023-05-18 at 11 58 10
Screenshot 2023-05-18 at 11 56 40
Screenshot 2023-05-18 at 11 54 46

**Review by bexsoft — APPROVED** [review]
LGTM, Issue is related to a misconfiguration in nginx, fixed and it worked.

**Comment by polaris-phecda** [comment]
@dvaldivia I observe that your modification depends on the `rewrite` configuration of Nginx. Is subpath configuration supported when I directly access the console?

**Comment by cesnietor** [comment]
Just posterity, the way the env are set didn't work so I had to do it like:
```
CI=true MINIO_BROWSER_REDIRECT_URL=http://localhost:8000/console/subpath/ MINIO_SERVER_URL=http://localhost:9000 ./minio server --console-address ":9090" ~/Data
```
Same nginx config shared above worked.

**Comment by ravindk89** [comment]
https://github.com/minio/docs/issues/865

We have an issue to document the updates to subpath behavior, but that is somewhat distinct from using either of those envvars - which last I checked, were mostly necessary for ensuring the Console and/or a remote OpenID Connect remote would correctly connect to the MinIO Server over specific hostnames.

**Comment by ravindk89** [comment]
To put a finer point on it - this *is* fragile/poorly documented, primarily because NGINX is not our product. We do need to make improvements and further clarify where to use the envvars in question, *but* we also cannot promise that our boilerplate NGINX configuration will work in all possible scenarios. We have to assume the implementer has access to NGINX expertise to figure out the gaps.

**Comment by nmattia** [comment]
looks like the parsing/checking of URL is a bit too strict. When setting the server URL to a local alias (without "subdomain"), I get the following:

> FATAL Invalid MINIO_SERVER_URL value is environment variable: URL contains unexpected resources, expected URL to be of http(s)://minio.example.com format: http://home.local/s3/

**Comment by ramondeklein** [comment]
@nmattia The reason this fails is that `MINIO_SERVER_URL` has to have the following characteristics:
- Scheme should be `http` or `https`.
- Path should be empty (this implies that the server cannot run on a sub-path).
- Query and fragment should be empty.

You try to run the server on a sub-path and that's not supported.

**Pull request merged**
