### PR TITLE
Created Help Box on Basic Dashboard guiding user to Prometheus documentation

### LINKED ISSUE #994: FR: Add link to docs when MINIO_PROMETHEUS_URL or CONSOLE_PROMETHEUS_URL is not set
A frequent question that keeps coming up is "why are metrics not showing in the console" due to users not knowing they need prometheus running and one of the aforementioned environment variables set.  When users do not have the env var set, we should display a banner with links to the docs for prometheus and setting the proper env var.

### PR DESCRIPTION
**Pull request by jinapurapu**
**What does this do?**
Adds a Help Box with links to documentation on enabling Prometheus to the Basic Dashboard that is shown when Prometheus metrics are not available to display.

Fixes #994 

**How does it look**
Screenshot from 2021-11-10 13-04-46
?

### CODE REVIEW

**Comment by dvaldivia** [comment]
Should we use the Tenant Icon on that box @oscarocastellanos ?

**Review by dvaldivia — APPROVED** [review]

**Comment by oscarocastellanos** [comment]
> Should we use the Tenant Icon on that box @oscarocastellanos ?

@dvaldivia 
I had a screen for when we didn't have Prometheus enabled. Maybe we can use the Prometheus logo instead https://xd.adobe.com/view/40e0ad3f-97a7-4394-8e3e-d9059e7b599d-15b3/

**Review by dvaldivia — APPROVED** [review]
Tested. LGTM

**Comment by dvaldivia** [comment]
IMG_2865

**Review by bexsoft — APPROVED** [review]
LGTM, works good

**Pull request merged**
