### PR TITLE
PVC Events API

### PR DESCRIPTION
**Pull request by adfost**
API for getting events of PVCs

### CODE REVIEW

**Review by dvaldivia — CHANGES_REQUESTED** [review]
A lot of these changes seem to be removing things recently added by the update to swagger `v0.28.0` make sure you are generating the new stubs with the latest swagger
```
➜ swagger version
version: v0.28.0
commit: 48a66e4bdbcde02c8c6c95ff9a08f64fe40b1b50
(base)  console git:(update-swagger) ✗ 
```

**Comment by dvaldivia** [comment]
please also rebase

**Review by dvaldivia — CHANGES_REQUESTED** [review]
I'm getting a 404 when calling the API


```
➜ curl 'http://localhost:9090/api/v1/namespaces/ns-1/tenants/new-tenant/pvcs/data0-new-tenant-pool-0-3/events' \
-X 'GET' \
-H 'Cookie: token=AYz9aZn1XU3ojFK798xSG6qbO9E2ZVoozMOKN2vV9egRFbc/KUu/K8YE9Jf+GKgVkhADcQJdh0/G95OWAaQR6VDvJin55Q=='
```

response

```
{"code":404,"message":"path /api/v1/namespaces/ns-1/tenants/new-tenant/pvcs/data0-new-tenant-pool-0-3/events was not found"}%    
```

**Review by dvaldivia — APPROVED** [review]
Tested. LGTM.

**Review by bexsoft — APPROVED** [review]
LGTM

**Pull request merged**
