### PR TITLE
Add support for manual edit of KES configuration file

### PR DESCRIPTION
**Pull request by Alevsk**
This PR adds the raw edit tab for the `Encryption` configuration of a tenant. Newest versions of KES add support to additional customization and variables via the KES `server-config.yaml`

## Create Tenant

Screenshot from 2022-10-03 17-57-47

## Update Tenant

Screenshot from 2022-10-03 17-57-04
Screenshot from 2022-10-03 17-57-19
Screenshot from 2022-10-06 17-05-49

Signed-off-by: Lenin Alevski <alevsk.8772@gmail.com>

### CODE REVIEW

**Review by kaankabalak — APPROVED** [review]
LGTM

**Review by bexsoft — CHANGES_REQUESTED** [review]
If I set an incorrect configuration in the RAW Edit box it allows me to continue. Is this expected? I think we should show an error message for this.

**Comment by Alevsk** [comment]
> If I set an incorrect configuration in the RAW Edit box it allows me to continue. Is this expected? I think we should show an error message for this.

At most i think we can validate the provided string its a valid yaml format but we don't have a way to check the values and the format it's fine, the only way to see if theres an error would be KES throwing an error

**Comment by Alevsk** [comment]
> If I set an incorrect configuration in the RAW Edit box it allows me to continue. Is this expected? I think we should show an error message for this.

Will think what can we do to validate user input :thinking:

**Comment by Alevsk** [comment]
@bexsoft added validation and also fixed a couple of issues related to returned error codes

**Review by bexsoft — APPROVED** [review]

**Review by kaankabalak — APPROVED** [review]

**Review by cniackz — APPROVED** [review]
LGTM

**Pull request merged**
