### PR TITLE
Fixed refresh button on ListObjects screen

### PR DESCRIPTION
**Pull request by jinapurapu**
Refresh button on ListObjects screen now reloads latest bucketInfo. 

https://user-images.githubusercontent.com/65002498/226708716-6fd070d6-e0f2-4056-b170-09d713e8b8da.mov

closes https://github.com/miniohq/engineering/issues/1181

### CODE REVIEW

**Comment by kaankabalak** [comment]
I'm not sure if I am doing anything wrong, however, even though it looks like an API request is being made now when the user clicks on the Refresh button which is great, I think the main problem seems to be that the count that comes in from the backend takes time to update to the correct value (took around 100 seconds on both cases below when I uploaded and deleted an object):

Screen Shot 2023-03-21 at 1 49 57 PM

Screen Shot 2023-03-21 at 1 52 24 PM

**Comment by jinapurapu** [comment]
> I'm not sure if I am doing anything wrong, however, even though it looks like an API request is being made now when the user clicks on the Refresh button which is great, I think the main problem seems to be that the count that comes in from the backend takes time to update to the correct value (took around 100 seconds on both cases below when I uploaded and deleted an object):
> 
> Screen Shot 2023-03-21 at 1 49 57 PM
> 
> Screen Shot 2023-03-21 at 1 52 24 PM

Yes, I will look into that further, as well as making more clear the situation with deleted versioned objects (these seem to remain in the object count without explanation to the user, causing mismatch between the visible objects and the number shown in the Bucket Info section). This PR is just to fix the non-functional refresh button to start.

**Comment by kaankabalak** [comment]
> Yes, I will look into that further, as well as making more clear the situation with deleted versioned objects (these seem to remain in the object count without explanation to the user, causing mismatch between the visible objects and the number shown in the Bucket Info section) to fix in future PRs. This PR is just to fix the non-functional refresh button to start.

Sounds good, I'll approve this PR as the lint failures seem to be unrelated 👍

**Review by kaankabalak — APPROVED** [review]

**Review by reivaj05 — APPROVED** [review]

**Review by bexsoft — APPROVED** [review]
LGTM, In the future we may need to simplify this in one call (perhaps adding this information to the websocket too. This may be handled in the update in real time task in future releases)

**Pull request merged**
