### PR TITLE
fix: crash in operator console for missing fsGroup

### PR DESCRIPTION
**Pull request by harshavardhana**
Bonus: Add support for "fsGroupChangePolicy"

### CODE REVIEW

**Review by Alevsk — APPROVED** [review]

**Comment by harshavardhana** [comment]
@bexsoft do you know why OpenUI tests are failing ?

**Comment by bexsoft** [comment]
> @bexsoft do you know why OpenUI tests are failing ?

I think this may be due to unexpected lowness in tenants page as it is not finding the items in the page. Let me see if any of this changes affect how the elements are rendered.

Can you try to rebase again?

**Comment by harshavardhana** [comment]
PTAL @dvaldivia @bexsoft

**Review by dvaldivia — DISMISSED** [review]

**Review by bexsoft — CHANGES_REQUESTED** [review]
Error trying to create tenant:
Screen Shot 2022-08-01 at 17 56 02

**Comment by harshavardhana** [comment]
> Error trying to create tenant: Screen Shot 2022-08-01 at 17 56 02

So this needs some UI changes as well ?

**Comment by bexsoft** [comment]
> > Error trying to create tenant: Screen Shot 2022-08-01 at 17 56 02
> 
> So this needs some UI changes as well ?

Yes, just adding the `fsGroupChangePolicy` to the create tenant request should be enough  as it is marked as required in the swagger definition

**Comment by harshavardhana** [comment]
> Yes, just adding the `fsGroupChangePolicy` to the create tenant request should be enough as it is marked as required in the swagger definition

I can add them as `optional` for `fsGroup` would that work?

**Review by bexsoft — APPROVED** [review]
LGTM

**Comment by harshavardhana** [comment]
@dvaldivia PTAL

**Review by dvaldivia — APPROVED** [review]

**Pull request merged**
