### PR TITLE
Anonymous Access

### PR DESCRIPTION
**Pull request by dvaldivia**
Screenshot 2023-01-25 at 10 46 12 AM

# Testing

1. Create a bucket `asdasd`
2. Upload some files to the bucket
3. Set the bucket anonymous acess to `readwrite`, `readonly`
4. Open an incognito and visit [http://localhost:5005/browser/asdasd](http://localhost:5005/browser/asdasd)

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

**Review by bexsoft — APPROVED** [review]

**Comment by jinapurapu** [comment]
Screen Shot 2023-01-25 at 11 27 54 AM
Tooltip advises to leave blank to apply to root, but Save button is disabled if prefix field left blank. What is the correct way to apply to bucket root?

**Comment by dvaldivia** [comment]
@jinapurapu mmm, I always use `/` which is equivalent, but perhaps we should make it so empty also is allowed? I didn't change anything about management in this PR

**Comment by jinapurapu** [comment]
I am unable to upload a file with readwrite set on the anonymous bucket 
Screen Shot 2023-01-25 at 11 57 34 AM

Screen Shot 2023-01-25 at 11 56 02 AM

**Review by bexsoft — CHANGES_REQUESTED** [review]
Please review @jinapurapu comments, Issue is visible on my side too.

**Comment by dvaldivia** [comment]
Fixed @jinapurapu @bexsoft

**Review by bexsoft — APPROVED** [review]
LGTM, Works good

**Comment by jinapurapu** [comment]
Is there any way to show that the user is inside a subpath? Only bucket name is shown despite going into prefix, shown here going into "test" folder. Also, if a readwrite or readonly policy in set on a subpath, but no policy is set for the overall bucket, I am not able to access the subpath.

Screen Shot 2023-01-27 at 12 05 44 PM
Screen Shot 2023-01-27 at 12 05 51 PM

**Comment by dvaldivia** [comment]
@jinapurapu per the design, we don't have breadcrums on anonymous mode

**Review by jinapurapu — APPROVED** [review]

**Comment by neel** [comment]
I want anonymous readonly access. So I did not add `readwrite`. I am getting xml output listing all files. Should I must add `readwrite`in order to get browser UI ?

**Pull request merged**
