### PR TITLE
Disabled Preview button for text files

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

Disabled Preview button for text files

### CODE REVIEW

**Review by reivaj05 — APPROVED** [review]

**Review by allanrogerr — DISMISSED** [review]
Simple fix :)

**Review by jinapurapu — DISMISSED** [review]

**Review by allanrogerr — APPROVED** [review]

**Review by jinapurapu — APPROVED** [review]

**Comment by jankap** [comment]
Why exactly has the preview been disabled?

**Comment by ianroberts** [comment]
What was the reasoning behind this decision?  I find the preview option very useful for plain text files as it means I can upload a `_README.txt` into folders that would otherwise be empty, explaining what sort of files should be dropped there by other people.  I suppose I could make a PDF instead, but why disable plain text?  Was this to fix some other CVE or something?

**Comment by cesnietor** [comment]
I'm trying to find out as well :D. I'm also curious about it. We'll share the context if we end up figuring out. but seems it was for security reasons but the reasons are not explained though. https://github.com/minio/console/issues/2021#issuecomment-1132942518.

**Pull request merged**
