### PR TITLE
Multiple fixes in resources browsing

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

- Fixed subpaths search & navigation
- Fixed a regression in object browser for object details panel reset
- Added a test for these cases

### CODE REVIEW

**Comment by cniackz** [comment]
`Workflow / Permissions Tests Part 3 (1.17.x, ubuntu-latest) (pull_request)` is stuck in this PR:

Screen Shot 2022-05-20 at 5 30 08 PM

**Comment by cniackz** [comment]
When it got stuck:

Screen Shot 2022-05-20 at 5 35 57 PM

**Review by cniackz — COMMENTED** [review]
Let's find out why `permissions-3` is getting stuck here

**Comment by cniackz** [comment]
If I run locally I see this failure in permissions-3:

```
 For user with Logs permissions
 ✓ Tools sidebar item exists
 ✓ Logs link exists in Tools page
 ✓ Logs page can be opened
 ✓ Log window exists in Logs page
 ✓ Node selector exists in Logs page

 Test resources policy
 ✖ User can only see permitted files in last path as expected

   1) The specified selector does not match any element in the DOM tree.
      
       > | Selector('h1')
         |   .withText('testcondition')
         |   .parent(4)
         |   .find('button:enabled')
         |   .withText('Browse')

      Browser: Chrome 101.0.4951.64 / macOS 10.15.7

         60 |    "User can only see permitted files in last path as expected",
         61 |    async (t) => {
         62 |      await t
         63 |        .useRole(roles.conditions2)
         64 |        .navigateTo(`http://localhost:9090/buckets`)
       > 65 |        .click(test1BucketBrowseButton)
         66 |        .click(
         67 |          Selector(".ReactVirtualized__Table__rowColumn").withText("firstlevel")
         68 |        )
         69 |        .expect(file.exists)
         70 |        .notOk()

         at <anonymous> (/Users/cniackz/console/portal-ui/tests/permissions-3/resourceTesting.ts:65:10)
         at <anonymous> (/Users/cniackz/console/portal-ui/tests/permissions-3/resourceTesting.ts:23:71)
         at __awaiter (/Users/cniackz/console/portal-ui/tests/permissions-3/resourceTesting.ts:19:12)
         at <anonymous> (/Users/cniackz/console/portal-ui/tests/permissions-3/resourceTesting.ts:61:17)


 ✖ User can browse from first level as policy has wildcard

   1) The specified selector does not match any element in the DOM tree.
      
       > | Selector('h1')
         |   .withText('testcondition')
         |   .parent(4)
         |   .find('button:enabled')
         |   .withText('Browse')

      Browser: Chrome 101.0.4951.64 / macOS 10.15.7

         110 |    );
         111 |  })("User can browse from first level as policy has wildcard", async (t) => {
         112 |    await t
         113 |      .useRole(roles.conditions1)
         114 |      .navigateTo(`http://localhost:9090/buckets`)
       > 115 |      .click(test1BucketBrowseButton)
         116 |      .click(
         117 |        Selector(".ReactVirtualized__Table__rowColumn").withText("firstlevel")
         118 |      )
         119 |      .expect(file.exists)
         120 |      .ok()

         at <anonymous> (/Users/cniackz/console/portal-ui/tests/permissions-3/resourceTesting.ts:115:8)
         at <anonymous> (/Users/cniackz/console/portal-ui/tests/permissions-3/resourceTesting.ts:23:71)
         at __awaiter (/Users/cniackz/console/portal-ui/tests/permissions-3/resourceTesting.ts:19:12)
         at <anonymous> (/Users/cniackz/console/portal-ui/tests/permissions-3/resourceTesting.ts:111:77)



 2/31 failed (3m 02s)

```

**Comment by cniackz** [comment]
Now, I am trying to move the failing test to a new folder, to isolate and see if same stuck problem is observed.

**Comment by bexsoft** [comment]
> If I run locally I see this failure in permissions-3:
> 
> ```
>  For user with Logs permissions
>  ✓ Tools sidebar item exists
>  ✓ Logs link exists in Tools page
>  ✓ Logs page can be opened
>  ✓ Log window exists in Logs page
>  ✓ Node selector exists in Logs page
> 
>  Test resources policy
>  ✖ User can only see permitted files in last path as expected
> 
>    1) The specified selector does not match any element in the DOM tree.
>       
>        > | Selector('h1')
>          |   .withText('testcondition')
>          |   .parent(4)
>          |   .find('button:enabled')
>          |   .withText('Browse')
> 
>       Browser: Chrome 101.0.4951.64 / macOS 10.15.7
> 
>          60 |    "User can only see permitted files in last path as expected",
>          61 |    async (t) => {
>          62 |      await t
>          63 |        .useRole(roles.conditions2)
>          64 |        .navigateTo(`http://localhost:9090/buckets`)
>        > 65 |        .click(test1BucketBrowseButton)
>          66 |        .click(
>          67 |          Selector(".ReactVirtualized__Table__rowColumn").withText("firstlevel")
>          68 |        )
>          69 |        .expect(file.exists)
>          70 |        .notOk()
> 
>          at <anonymous> (/Users/cniackz/console/portal-ui/tests/permissions-3/resourceTesting.ts:65:10)
>          at <anonymous> (/Users/cniackz/console/portal-ui/tests/permissions-3/resourceTesting.ts:23:71)
>          at __awaiter (/Users/cniackz/console/portal-ui/tests/permissions-3/resourceTesting.ts:19:12)
>          at <anonymous> (/Users/cniackz/console/portal-ui/tests/permissions-3/resourceTesting.ts:61:17)
> 
> 
>  ✖ User can browse from first level as policy has wildcard
> 
>    1) The specified selector does not match any element in the DOM tree.
>       
>        > | Selector('h1')
>          |   .withText('testcondition')
>          |   .parent(4)
>          |   .find('button:enabled')
>          |   .withText('Browse')
> 
>       Browser: Chrome 101.0.4951.64 / macOS 10.15.7
> 
>          110 |    );
>          111 |  })("User can browse from first level as policy has wildcard", async (t) => {
>          112 |    await t
>          113 |      .useRole(roles.conditions1)
>          114 |      .navigateTo(`http://localhost:9090/buckets`)
>        > 115 |      .click(test1BucketBrowseButton)
>          116 |      .click(
>          117 |        Selector(".ReactVirtualized__Table__rowColumn").withText("firstlevel")
>          118 |      )
>          119 |      .expect(file.exists)
>          120 |      .ok()
> 
>          at <anonymous> (/Users/cniackz/console/portal-ui/tests/permissions-3/resourceTesting.ts:115:8)
>          at <anonymous> (/Users/cniackz/console/portal-ui/tests/permissions-3/resourceTesting.ts:23:71)
>          at __awaiter (/Users/cniackz/console/portal-ui/tests/permissions-3/resourceTesting.ts:19:12)
>          at <anonymous> (/Users/cniackz/console/portal-ui/tests/permissions-3/resourceTesting.ts:111:77)
> 
> 
> 
>  2/31 failed (3m 02s)
> ```

I've been struggling with this test, for some reason locally it only runs if I change the path from where the files are being uploaded to the bucket. If we put correct paths, test start passing locally but in the server the hang continues. 

If we put the correct paths to start uploading from the server, first test passes, but second test for some reason doesn't display anything and it hangs again.

**Comment by cniackz** [comment]
The old trick, when isolating TestCafe tests, normally they tend to pass and run much faster since they are executed in parallel rather than pilled up in the same folder for sequential execution:

Screen Shot 2022-05-20 at 6 27 02 PM

**Review by cniackz — DISMISSED** [review]
LGTM, fixed the stucked test by moving it to a new folder, folder 7.

**Comment by bexsoft** [comment]
> LGTM, fixed the stucked test by moving it to a new folder, folder 7.

Thank you! =D

**Comment by cniackz** [comment]
Just wanted to confirm it is the right test and it is:

Screen Shot 2022-05-20 at 6 46 57 PM

```
 Running tests in:
 - Chrome 101.0.4951.64 / Linux 0.0

 Test resources policy
 ✓ User can only see permitted files in last path as expected
 ✓ User can browse from first level as policy has wildcard


 2 passed (11s)
```

**Review by cniackz — APPROVED** [review]
LGTM

**Review by Alevsk — APPROVED** [review]

**Pull request merged**
