### PR TITLE
Added speedtest functionality in console & updated diagnostic page styles

### LINKED ISSUE #461: Benchmark Module
This page will be used to run and display Warp reports about the MinIO cluster, further discussion about what kind of information we will display is need it.

benchmark

This `Benchmark` page will be available under a new category called `Subscription Network` in the Menu and be part of the Subnet Integration modules

### PR DESCRIPTION
**Pull request by bexsoft**
fixes #461 

## What does this do?

Adds speedtest functionality in console & updates diagnostic page styles 

**NOTE:** To test this we require the latest version of MinIO. Please run on 9090 port as WS is required
## How does it look?

Screen Shot 2021-11-10 at 16 08 54
Screen Shot 2021-11-10 at 16 08 47
Screen Shot 2021-11-10 at 16 08 43
Screen Shot 2021-11-10 at 16 07 21
Screen Shot 2021-11-10 at 16 07 16
Screen Shot 2021-11-10 at 16 06 45
Screen Shot 2021-11-10 at 16 06 37
Screen Shot 2021-11-10 at 16 06 29

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

### CODE REVIEW

**Comment by krishnasrinivas** [comment]
@bexsoft could you updated the screenshots with the latest screenshots?

**Review by dvaldivia — APPROVED** [review]
Tested. LGTM.

**Review by dvaldivia — APPROVED** [review]

**Review by dvaldivia — APPROVED** [review]

**Review by dvaldivia — APPROVED** [review]

**Review by Alevsk — APPROVED** [review]

**Comment by harshavardhana** [comment]
when do we release? 🍰

**Comment by dvaldivia** [comment]
@harshavardhana sooonish hahaha tonight?

**Pull request merged**
