### PR TITLE
Improve change password  user experience

### PR DESCRIPTION
**Pull request by prakashsvmx**
improve change password  user experience and add doc reference to rotating credentials for `MINIO_ROOT_USER`.

Fixes https://github.com/minio/console/issues/3053

image

### CODE REVIEW

**Review by bexsoft — APPROVED** [review]
LGTM

**Comment by cesnietor** [comment]
When current password is wrong we show 403 Forbidden, can we show the message returned instead?
`"error please check your current password"`, to give the user more details.

**Comment by cesnietor** [comment]
When console is using same credentials as root password, it doesn't allow you to update them.
Screenshot 2023-09-21 at 1 18 05 PM
Screenshot 2023-09-21 at 1 15 03 PM

If we know that in advance, then we shouldn't disable the fields or not show them.

**Comment by cesnietor** [comment]
If I have a new user with no policies assigned to them, and try to update their password, the logs say:
```
ErrorWithContext:error please check your current password
%!(EXTRA <nil>, madmin.ErrorResponse=Access Denied.)
```
And the UI show the 403 forbidden. If it's not allowed shouldn't we disable the feature for them? So that they don't even try to do it.

**Comment by prakashsvmx** [comment]
@cesnietor 
I have updated to show the correct error message.

for other items:
- In console i could not find a way to know if the logged in user is with root credentials.
- The permissions for change password and create access keys are provided with `conole-ui` by default. so we will not be able to disable it. ( even when no policies assigned)
-

**Review by cesnietor — APPROVED** [review]

**Comment by cesnietor** [comment]
Thanks @prakashsvmx  lgtm

**Review by bexsoft — APPROVED** [review]

**Pull request merged**
