### PR TITLE
Fix build after swagger codegen

### PR DESCRIPTION
**Pull request by donatello**
This fixes the changes to the swagger generated files.

### CODE REVIEW

**Review by reivaj05 — DISMISSED** [review]

**Comment by donatello** [comment]
@cniackz Could you take a look at this? I am not able to tell how the CI failures are related to the changes in this PR.

**Review by bexsoft — CHANGES_REQUESTED** [review]
I'm not able to run / build console server by the following error:

```
# github.com/mattn/go-ieproxy
../../../../go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.7/ieproxy.go:36:9: undefined: getConf
../../../../go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.7/ieproxy.go:41:9: undefined: reloadConf
../../../../go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.7/ieproxy.go:48:2: undefined: overrideEnvWithStaticProxy
../../../../go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.7/ieproxy.go:53:13: psc.findProxyForURL undefined (type *ProxyScriptConf has no field or method findProxyForURL, but does have FindProxyForURL)
```

**Comment by donatello** [comment]
> I'm not able to run / build console server by the following error:
> 
> ```
> # github.com/mattn/go-ieproxy
> ../../../../go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.7/ieproxy.go:36:9: undefined: getConf
> ../../../../go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.7/ieproxy.go:41:9: undefined: reloadConf
> ../../../../go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.7/ieproxy.go:48:2: undefined: overrideEnvWithStaticProxy
> ../../../../go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.7/ieproxy.go:53:13: psc.findProxyForURL undefined (type *ProxyScriptConf has no field or method findProxyForURL, but does have FindProxyForURL)
> ```

This doesn't seem to happen on my system. Not sure why all the deps got upgraded, will see if I can downgrade and update the PR. @bexsoft

**Comment by donatello** [comment]
@bexsoft Could you try now?

**Comment by bexsoft** [comment]
Issue with deps fixed. Testing

**Review by bexsoft — APPROVED** [review]
Sanity check LGTM. Need to verify specific operator workflow issues

**Review by reivaj05 — APPROVED** [review]

**Review by bexsoft — CHANGES_REQUESTED** [review]
Workflow issues are related to this change, Tests need to be updated with these changes

**Comment by donatello** [comment]
The remaining failure is expected as changes in minio are required. There is a linked PR. We can take this in.

**Review by bexsoft — APPROVED** [review]

**Pull request merged**
