### PR TITLE
Upgrade jsonwebtoken - vulnerabilities found in current version

### PR DESCRIPTION
**Pull request by reivaj05**
yarn audit is failing because there are vulnerabilities in jsonwebtoken package
https://github.com/minio/console/actions/runs/3759184826/jobs/6389691278

### CODE REVIEW

**Review by harshavardhana — COMMENTED** [review]
can you state the reason for upgrade?

**Comment by reivaj05** [comment]
> can you state the reason for upgrade?

https://github.com/minio/console/actions/runs/3759184826/jobs/6389691278

**Comment by harshavardhana** [comment]
> https://github.com/minio/console/actions/runs/3759184826/jobs/6389691278

@reivaj05 put that in the title of the PR its easier for others to get the gist of why only one dependency is being upgraded.

**Review by dilverse — DISMISSED** [review]

**Review by pjuarezd — DISMISSED** [review]

**Review by harshavardhana — DISMISSED** [review]

**Review by bexsoft — CHANGES_REQUESTED** [review]
Can you please include this change in resolutions section from `package.json` too?

`"testcafe/**/jsonwebtocken":"^9.0.0"`

Thank you!

**Comment by harshavardhana** [comment]
There is some unrelated test failure

```
=== RUN   TestEditSiteReplicationInfo
Edit Site Replication
Editing a valid site deployment id:: 151d3e61-ca4a-416d-b00d-97bc34923df0
=== RUN   TestEditSiteReplicationInfo/Edit_an_existing_valid_site
TestEditSiteReplicationInfo:  500
=== RUN   TestEditSiteReplicationInfo/Edit_with_an_invalid_site_endpoint
TestEditSiteReplicationInfo:  500
=== CONT  TestEditSiteReplicationInfo
    admin_api_int_replication_test.go:287: 
        	Error Trace:	/home/runner/work/console/console/replication/admin_api_int_replication_test.go:287
        	Error:      	Should NOT be empty, but was <nil>
        	Test:       	TestEditSiteReplicationInfo
=== RUN   TestEditSiteReplicationInfo/Edit_with_an_invalid_empty_site_
TestEditSiteReplicationInfo:  500
--- FAIL: TestEditSiteReplicationInfo (0.37s)
    --- PASS: TestEditSiteReplicationInfo/Edit_an_existing_valid_site (0.12s)
    --- PASS: TestEditSiteReplicationInfo/Edit_with_an_invalid_site_endpoint (0.12s)
    --- PASS: TestEditSiteReplicationInfo/Edit_with_an_invalid_empty_site_ (0.12s)
=== RUN   TestDeleteSiteReplicationInfo
```

**Review by pjuarezd — APPROVED** [review]

**Review by dvaldivia — APPROVED** [review]

**Pull request merged**
