### PR TITLE
Updated OpenID UX

### LINKED ISSUE #2936: OIDC env variables not correctly represented in UI
## Expected Behavior
Environment variables correctly alter the configuration and are correctly displayed in the MinIO console.

## Current Behavior
When setting environment variables in the official helm chart i.e. `MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC` to `on` as mentioned in https://github.com/minio/docs/issues/913 the console does not display an enabled switch. I have discovered that this also applies to `MINIO_IDENTITY_OPENID_CLIENT_SECRET` (no text is shown). Other env vars might also be affected.

## Steps to Reproduce (for bugs)
1. Set all possible OIDC environment variables in the official helm chart (set variables not available under `oidc` section in the `environment` section)
2. Install the helm chart
3. Open the MinIO console and check the default OIDC configuration

## Regression
Unknown.

## Your Environment
* MinIO version used: RELEASE.2023-07-07T07-13-57Z
* Server setup and configuration: MinIO helm chart 5.0.11 on a 1.27.2 k3s cluster (3x RaspberryPi 4B)
* Operating System and version: 6.1.21-v8+ aarch64 GNU/Linux

### PR DESCRIPTION
**Pull request by bexsoft**
fixes #2936

## What does this do?

- Display ENV variables set in configuration
- Removed Password empty placeholders
- Added notification to re-enter password when modifying OpenID configuration

## How does it look?

Screenshot 2023-09-18 at 18 56 50
Screenshot 2023-09-18 at 18 56 43
Screenshot 2023-09-18 at 18 56 31
Screenshot 2023-09-18 at 18 56 28
Screenshot 2023-09-18 at 18 56 26

### CODE REVIEW

**Comment by cniackz** [comment]
I will be reviewing this today.

**Comment by cniackz** [comment]
Ok tested with `KeyCloak` and yes this works as intended, I can login via `Keycloak` with steps provided in https://github.com/cniackz/public/wiki/How-to-test-MinIO-SSO-keycloak and I can see those same signs that I can't edit, update or delete if set via env vars:

Screenshot 2023-09-22 at 1 07 10 PM

Screenshot 2023-09-22 at 1 07 20 PM

**Review by cniackz — APPROVED** [review]
Tested locally and it works; should we fix tests on a new PR?:

[Workflow / playwright] is failing
[Workflow / Integration Tests with Latest Distributed MinIO (1.21.x) (pull_request)] is failing
[Workflow / Site Replication Test (1.21.x) (pull_request)] is failing

**Comment by bexsoft** [comment]
> Tested locally and it works; should we fix/update tests on a new PR?:
> 
> `[Workflow / playwright]` is failing `[Workflow / Integration Tests with Latest Distributed MinIO (1.21.x) (pull_request)]` is failing `[Workflow / Site Replication Test (1.21.x) (pull_request)]` is failing

Yes, we need to review these failures as it started happening after a replication change was merged in server

**Review by cesnietor — APPROVED** [review]

**Pull request merged**
