### PR TITLE
Release v0.15.5

### PR DESCRIPTION
**Pull request by dvaldivia**
Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

**Review by prakashsvmx — DISMISSED** [review]

**Review by bexsoft — DISMISSED** [review]
Please wait for the Path PR (https://github.com/minio/console/pull/1885) to get merged

**Review by cniackz — APPROVED** [review]
LGTM

**Comment by cniackz** [comment]
https://github.com/minio/console/pull/1885 got merged already

**Review by bexsoft — CHANGES_REQUESTED** [review]
Please update assets

**Pull request closed without merging**
