### PR TITLE
Fixed an issue with subpaths in resources policies

### LINKED ISSUE #2835: Console weird behaviour for user under restricted policy
## Expected Behavior
Console should not show not existing objects

## Current Behavior
I defined a policy that allows access only to a specific path in the bucket

After that, I assigned a user that policy and then I tried to verify the access by using mc command line util. Everything is coherent with the policy: I cannot access any home folders other than Davide one.

When I login with the same user into the MINIO console even if I cannot access objects out of his scope policy I see unexpected objects

## Steps to Reproduce (for bugs)
I create a `my-company` bucket and then a policy copying it verbatim from [here](https://aws.amazon.com/blogs/security/writing-iam-policies-grant-access-to-user-specific-folders-in-an-amazon-s3-bucket/) 

this is the mc output
image

while this is what I see in console
image
image
image

## Your Environment

* Version used (`minio --version`): `RELEASE.2023-03-24T21-41-23Z (go1.19.7 linux/amd64)`
* Server setup and configuration:
* Operating System and version (`uname -a`): `Linux srvcosr012 4.9.0-2-amd64 minio/minio#1 SMP Debian 4.9.18-1 (2017-03-30) x86_64 GNU/Linux`

### PR DESCRIPTION
**Pull request by bexsoft**
fixes #2835 

## What does this do?

Fixes an issue where resources policies can return incorrect items in subpaths

## How to test

1. In console create a policy with this content and assign it to a user
```json
{
 "Version":"2012-10-17",
 "Statement": [
   {
     "Sid": "AllowUserToSeeBucketListInTheConsole",
     "Action": ["s3:ListAllMyBuckets", "s3:GetBucketLocation"],
     "Effect": "Allow",
     "Resource": ["arn:aws:s3:::*"]
   },
  {
     "Sid": "AllowRootAndHomeListingOfCompanyBucket",
     "Action": ["s3:ListBucket"],
     "Effect": "Allow",
     "Resource": ["arn:aws:s3:::my-company"],
     "Condition":{"StringEquals":{"s3:prefix":["","home/", "home/David"],"s3:delimiter":["/"]}}
    },
   {
     "Sid": "AllowListingOfUserFolder",
     "Action": ["s3:ListBucket"],
     "Effect": "Allow",
     "Resource": ["arn:aws:s3:::my-company"],
     "Condition":{"StringLike":{"s3:prefix":["home/David/*"]}}
   },
   {
     "Sid": "AllowAllS3ActionsInUserFolder",
     "Effect": "Allow",
     "Action": ["s3:*"],
     "Resource": ["arn:aws:s3:::my-company/home/David/*"]
   }
 ]
}
```
2. In your local MinIO instance, create a bucket called `my-company` and create a home folder inside it
3. Inside the home folder, create some folders, one of the must be called `David`. Add files to them
4. Login as the user with the assigned policy and navigate to `home/David` inside `my-company` bucket. Files must be seen
5. Try to navigate to a different folder inside `home`, an Access Denied error must be seen.

### CODE REVIEW

**Comment by cesnietor** [comment]
We found while testing that if the first time you login, you go to the `my-company/home/David/` path and then you go back and try to access other buckets, it for some reasons starts listing the `home` folder in the other buckets as well. this doesn't happen if you access other buckets first (for some reason).

Screenshot 2023-06-06 at 5 22 56 PM

**Comment by bexsoft** [comment]
> We found while testing that if the first time you login, you go to the `my-company/home/David/` path and then you go back and try to access other buckets, it for some reasons starts listing the `home` folder in the other buckets as well. this doesn't happen if you access other buckets first (for some reason).
> 
> Screenshot 2023-06-06 at 5 22 56 PM

This issue was not related to this change, fixed anyway in this PR

**Comment by bexsoft** [comment]
> > We found while testing that if the first time you login, you go to the `my-company/home/David/` path and then you go back and try to access other buckets, it for some reasons starts listing the `home` folder in the other buckets as well. this doesn't happen if you access other buckets first (for some reason).
> > Screenshot 2023-06-06 at 5 22 56 PM
> 
> This issue was not related to this change, fixed anyway in this PR 

cc @cesnietor @prakashsvmx

**Comment by prakashsvmx** [comment]
Once we refresh the page, the path objects are not loaded but the breadcrumb displays the path.

**Review by cesnietor — APPROVED** [review]
LGTM

**Comment by prakashsvmx** [comment]
Interestingly, it happens with the user who has full (e.g root user) access 
@cesnietor @bexsoft 

- As an admin user,  Create bucket `my-company`   -> Browse the bucket ->  Create path `home/David`  upload files under `David`.
- Note: Clicking the `Refresh`  button  works as expected at this point.
- Now just refresh the page (Browser reload) and observe the breadcrumb and the object/folder list. 
- Also uploading the a file at this point navigates to the object list at the correct path.


It is not happening with this  user where the resource policy is applied.

As a user with full access, create the policy as specified in description, 
create a user (user1) and associate the policy


https://github.com/minio/console/assets/23444145/03c283f7-3115-4c1b-b6ed-2ed944c863e8

**Review by kaankabalak — APPROVED** [review]

**Pull request merged**
