### PR TITLE
Added View action to groups table in UserDetails

### PR DESCRIPTION
**Pull request by jinapurapu**

### CODE REVIEW

**Review by prakashsvmx — APPROVED** [review]
Tested. Changes look good to me :+1:

**Review by bexsoft — APPROVED** [review]
LGTM

**Review by Alevsk — APPROVED** [review]

**Comment by cniackz** [comment]
Tested, good now I can go back and forth between user and group

**Review by cniackz — APPROVED** [review]
LGTM
Tested, good now I can go back and forth between user and group

**Pull request merged**
