### PR TITLE
Release v0.13.3

### PR DESCRIPTION
**Pull request by dvaldivia**
Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

**Review by harshavardhana — DISMISSED** [review]

**Review by bexsoft — APPROVED** [review]
LGTM

**Comment by jinapurapu** [comment]
Screenshot from 2022-01-19 12-15-09
Should be "Number of Nodes"

**Comment by harshavardhana** [comment]
> Should be "Number of Nodes"

Let's fix the typo in a separate PR @dvaldivia @jinapurapu

**Review by bexsoft — CHANGES_REQUESTED** [review]
Issue found

**Comment by dvaldivia** [comment]
rebased. PTAL @harshavardhana @bexsoft

**Review by bexsoft — APPROVED** [review]
LGTM

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
