### PR TITLE
Site replication API

### PR DESCRIPTION
**Pull request by prakashsvmx**
Site replication API
- Add Sites 
- Edit an endpoint
- Delete all/one site
- List of sites

Note: I will update the CI/CD steps for testing after discussing with @cniackz

### CODE REVIEW

**Review by cniackz — CHANGES_REQUESTED** [review]
We need to change and add more servers for the multi container MinIO Server architecture required by replication, I will be into that today. Tomorrow I will pair/synch with Prakash on this.

**Review by cniackz — APPROVED** [review]
It looks go to me, just let's fix the `EditSiteReplicationInfo` to work

**Comment by prakashsvmx** [comment]
@cesnietor Thank you so much for all the CI help and validating the tests.

**Comment by dvaldivia** [comment]
Wrong Cesar @prakashsvmx hahahaha I think you meant @cniackz, both are MinIO at heart though ❤️

**Review by jinapurapu — CHANGES_REQUESTED** [review]

**Review by bexsoft — APPROVED** [review]

**Review by dvaldivia — APPROVED** [review]

**Pull request merged**
