### PR TITLE
Release v0.21.2

### PR DESCRIPTION
**Pull request by dvaldivia**
Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

**Review by bexsoft — CHANGES_REQUESTED** [review]
Lets wait until https://github.com/minio/console/pull/2428 gets merged

**Review by bexsoft — APPROVED** [review]
As discussed, will send this change right away, menu changes will be available in an upcoming release

**Review by reivaj05 — APPROVED** [review]

**Comment by harshavardhana** [comment]
The inspect tests are not passing

```
=== CONT  TestInspect
    inspect_test.go:100: 
        	Error Trace:	/home/runner/work/console/console/integration/inspect_test.go:100
        	Error:      	Not equal: 
        	            	expected: 500
        	            	actual  : 200
        	Test:       	TestInspect
=== RUN   TestInspect/Test_Empty_Path
--- FAIL: TestInspect (0.04s)
    --- PASS: TestInspect/Test_Invalid_Path (0.01s)
    --- PASS: TestInspect/Test_Invalid_characters_in_Path (0.01s)
    --- PASS: TestInspect/Test_valid_bucket (0.01s)
    --- PASS: TestInspect/Test_Empty_Path (0.01s)
```

**Review by bexsoft — APPROVED** [review]
LGTM

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
