### PR TITLE
UI site replication

### PR DESCRIPTION
**Pull request by prakashsvmx**
UI for site replication

How does it look:

S1
S2
image

S4
image

Site Replication status would be in a new PR.

### CODE REVIEW

**Review by oscarocastellanos — APPROVED** [review]
LGTM

**Comment by dvaldivia** [comment]
@oscarocastellanos my only concern is that the `Delete` an `Edit` action buttons are different from everywhere else in the UI, should we adopt those squared icon buttons instead of the flat one or the circle ones? (which we should also make consistent btw hahaha)
Screen Shot 2022-04-07 at 10 19 37 AM

Screen Shot 2022-04-07 at 10 20 00 AM

**Comment by oscarocastellanos** [comment]
> @oscarocastellanos my only concern is that the `Delete` an `Edit` action buttons are different from everywhere else in the UI, should we adopt those squared icon buttons instead of the flat one or the circle ones? (which we should also make consistent btw hahaha) Screen Shot 2022-04-07 at 10 19 37 AM
> 
> Screen Shot 2022-04-07 at 10 20 00 AM

You're right @dvaldivia, this slipped past me. Yeah, we should stick to the circle ones and try to keep them consistent everywhere.

**Review by oscarocastellanos — CHANGES_REQUESTED** [review]
Please, let's use the action buttons for delete as circular style, as we use on other screens:
Captura de Pantalla 2022-04-07 a la(s) 12 26 39

**Comment by prakashsvmx** [comment]
@dvaldivia  , @oscarocastellanos  - I will continue to update the pages for consistency

**Review by dvaldivia — APPROVED** [review]

**Review by oscarocastellanos — APPROVED** [review]
LGTM

**Pull request merged**
