### PR TITLE
LDAP Page improvements

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

- Removed multiple LDAP support
- Fixed add LDAP configuration
- Fixed Edit LDAP configuration
- Fixed retrieve LDAP configuration parameters
- Fixed reset LDAP configuration support
- Added Entities search support

## How does it look?

Screenshot 2023-03-14 at 20 22 17
Screenshot 2023-03-14 at 20 21 59
Screenshot 2023-03-14 at 20 21 51
Screenshot 2023-03-14 at 20 21 41
Screenshot 2023-03-14 at 20 21 37
Screenshot 2023-03-14 at 20 21 29
Screenshot 2023-03-14 at 20 21 25

### CODE REVIEW

**Comment by donatello** [comment]
Does this already work without https://github.com/minio/minio/pull/16805 ?

**Comment by bexsoft** [comment]
> Does this already work without [minio/minio#16805](https://github.com/minio/minio/pull/16805) ?

Enable / Disable functionality is not enabled yet in this PR.

**Comment by bexsoft** [comment]
Enable / Disable LDAP will be activated in a following PR

**Comment by bexsoft** [comment]
> @bexsoft Just not sure why we need the little clock? image

Server returns a timestamp of the query, We may need another clock icon for this

**Pull request merged**
