### PR TITLE
Update Settings Page components

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

Updated Settings page components to use mds

## How does it look?
Screenshot 2023-08-08 at 21 14 29
Screenshot 2023-08-08 at 21 14 25
Screenshot 2023-08-08 at 21 14 18

### CODE REVIEW

**Review by kaankabalak — APPROVED** [review]
LGTM

**Comment by kaankabalak** [comment]
Seems like the dead code check is failing for the React Code Has No Warnings & Prettified test:
```
$ ts-prune -s consoleApi.ts | (! grep -v 'used in module')
src/screens/Console/Common/VerticalTabs/VerticalTabs.tsx:181 - default
error Command failed with exit code 1.
```

**Comment by bexsoft** [comment]
> Seems like the dead code check is failing for the React Code Has No Warnings & Prettified test:
> 
> ```
> $ ts-prune -s consoleApi.ts | (! grep -v 'used in module')
> src/screens/Console/Common/VerticalTabs/VerticalTabs.tsx:181 - default
> error Command failed with exit code 1.
> ```

Solved

**Review by cesnietor — APPROVED** [review]
Tested LGTM

**Review by reivaj05 — APPROVED** [review]

**Pull request merged**
