### PR TITLE
fix: passing correct httpClient, do not use DefaultClients

### PR DESCRIPTION
**Pull request by harshavardhana**
most of our deployments use custom certificates, using DefaultClient 
makes it virtually impossible to make the share URL feature work.

This PR fixes this behavior during implementation.

Bonus: Reuse transports inside the console; will add more changes to 
take custom transport inputs in subsequent PR.

### CODE REVIEW

**Comment by harshavardhana** [comment]
```
15s
5s
Run npx testcafe "chrome:headless" web-app/tests/permissions-2/ -q --skip-js-errors -c 3
  npx testcafe "chrome:headless" web-app/tests/permissions-2/ -q --skip-js-errors -c 3
  shell: /usr/bin/bash -e {0}
ERROR Cannot prepare tests due to the following error:

Error: TypeScript compilation failed.
/home/runner/work/console/console/web-app/tests/utils/functions.ts (37, 5[1](https://github.com/minio/console/actions/runs/8899619047/job/24439524419?pr=3319#step:9:1)): Expected 1-3 arguments, but got 4.
/home/runner/work/console/console/web-app/tests/utils/functions.ts (66, 68): Expected 3-4 arguments, but got 5.
```

Can you guide me on this failure @kaankabalak ?

**Comment by kaankabalak** [comment]
> ```
> 15s
> 5s
> Run npx testcafe "chrome:headless" web-app/tests/permissions-2/ -q --skip-js-errors -c 3
>   npx testcafe "chrome:headless" web-app/tests/permissions-2/ -q --skip-js-errors -c 3
>   shell: /usr/bin/bash -e {0}
> ERROR Cannot prepare tests due to the following error:
> 
> Error: TypeScript compilation failed.
> /home/runner/work/console/console/web-app/tests/utils/functions.ts (37, 5[1](https://github.com/minio/console/actions/runs/8899619047/job/24439524419?pr=3319#step:9:1)): Expected 1-3 arguments, but got 4.
> /home/runner/work/console/console/web-app/tests/utils/functions.ts (66, 68): Expected 3-4 arguments, but got 5.
> ```
> 
> Can you guide me on this failure @kaankabalak ?

Checking, my first impression is that this might've been caused by the new minio-js release, will keep you updated 👍

**Comment by kaankabalak** [comment]
@harshavardhana, will send in a PR to fix the test failures 👍

**Comment by harshavardhana** [comment]
> @harshavardhana, the tests seem to be failing as some of the function definitions have changed with the new minio-js release. Will send in a PR to resolve TypeScript compilation failed error 👍
> 
> For now, as a stopgap measure, we can replace `yarn add minio` in the `.github/workflows/jobs.yaml` file with `yarn add minio@7.1.3` to fix these failures.

thanks @kaankabalak updated the PR with `yarn add minio@7.1.3`

**Comment by harshavardhana** [comment]
This PR adds a way for MinIO server to pass the right HTTP transport this allows for full removal of MINIO_SERVER_URL

**Review by prakashsvmx — APPROVED** [review]

**Review by vadmeste — APPROVED** [review]
LGTM

**Pull request merged**
