### PR TITLE
Enabled Delete selected version functionality

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?
Enabled Delete selected version functionality

## How does it look?

Screen Shot 2022-03-16 at 19 13 13
Screen Shot 2022-03-16 at 19 13 01
Screen Shot 2022-03-16 at 19 12 53

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

### CODE REVIEW

**Review by Alevsk — DISMISSED** [review]

**Comment by prakashsvmx** [comment]
@oscarocastellanos 
The actions look ambiguous ( Preview, Download, Share ) when viewing object versions.
<summary> Delete marker Delete option  <summary>

<details> 


image

</details>

@bexsoft 
Delete marker version cannot be deleted from versions panel but can be deleted from main list using Delete all versions toggle in the modal

<summary> Delete marker Delete option <summary>

<details>

image

</details>

**Review by prakashsvmx — DISMISSED** [review]
LGTM.

**Comment by oscarocastellanos** [comment]
> @oscarocastellanos the actions are common for every item just ( enabled/disabled) so we can move the restore on every item to the right panel . and remove all the icons on each item. ?

You're right @prakashsvmx , they're redundant. Maybe we can rid of all those icons, but then we might start thinking on implementing the same sidebar to most of the screens. Thoughts @bexsoft?

**Comment by bexsoft** [comment]
> @oscarocastellanos The actions look ambiguous ( Preview, Download, Share ) when viewing object versions.
> 
> Version actions and side panel actions
> @bexsoft Delete marker version cannot be deleted from versions panel but can be deleted from main list using Delete all versions toggle in the modal
> 
> Delete marker Delete option

Enabled button when selected version has delete marker. button still disabled when latest version is delete_marker and no version has been selected

Screen Shot 2022-03-17 at 13 39 02

**Comment by oscarocastellanos** [comment]
> > > @oscarocastellanos the actions are common for every item just ( enabled/disabled) so we can move the restore on every item to the right panel . and remove all the icons on each item. ?
> > 
> > 
> > You're right @prakashsvmx , they're redundant. Maybe we can rid of all those icons, but then we might start thinking on implementing the same sidebar to most of the screens. Thoughts @bexsoft?
> 
> @oscarocastellanos Yes, I think those actions are redundant there after clicking one specific version, on the other side this helps to avoid clicking multiple times to get an action done when you know what you want to do
> 
> I think that if we remove them, we will have some empty space there that will look odd in the design.

@prakashsvmx @bexsoft Ahh, we have come to an interesting conundrum. Consider: We're also adding size and date as a column, so the empty space would not be a problem in the end

Captura de Pantalla 2022-03-17 a la(s) 13 45 57

**Comment by bexsoft** [comment]
> > > > @oscarocastellanos the actions are common for every item just ( enabled/disabled) so we can move the restore on every item to the right panel . and remove all the icons on each item. ?
> > > 
> > > 
> > > You're right @prakashsvmx , they're redundant. Maybe we can rid of all those icons, but then we might start thinking on implementing the same sidebar to most of the screens. Thoughts @bexsoft?
> > 
> > 
> > @oscarocastellanos Yes, I think those actions are redundant there after clicking one specific version, on the other side this helps to avoid clicking multiple times to get an action done when you know what you want to do
> > I think that if we remove them, we will have some empty space there that will look odd in the design.
> 
> @prakashsvmx @bexsoft Ahh, we have come to an interesting conundrum. Consider: We're also adding size and date as a column, so the empty space would not be a problem in the end
> 
> Captura de Pantalla 2022-03-17 a la(s) 13 45 57

@oscarocastellanos Yeah, We can work on that change in a new task

**Review by prakashsvmx — APPROVED** [review]
LGTM :+1:

**Review by dvaldivia — APPROVED** [review]

**Pull request merged**
