### PR TITLE
Add Tenant Health Details

### PR DESCRIPTION
**Pull request by dvaldivia**
Screen Shot 2021-06-01 at 4 40 17 PM

Screen Shot 2021-06-01 at 4 40 24 PM

Screen Shot 2021-06-01 at 4 48 59 PM

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

**Comment by dvaldivia** [comment]
@belvid we need an official `Green, Yellow, Red` shade, I think we do have an official Red for errors, but not the other two

**Review by bexsoft — APPROVED** [review]

**Comment by belvid** [comment]
Here you go boys:

G: #32c787
Y:  #ffb300
R: #f75155

**Comment by dvaldivia** [comment]
@belvid we already use `#dc1f2e` for red, which is a little more red than `#f75155`, should we make that the default?

**Comment by dvaldivia** [comment]
Screen Shot 2021-06-02 at 2 08 33 PM
Screen Shot 2021-06-02 at 2 08 24 PM

**Comment by belvid** [comment]
Yes, please use #f75155 globally.

**Review by bexsoft — APPROVED** [review]

**Review by Alevsk — APPROVED** [review]
LGTM

**Pull request merged**
