### PR TITLE
Fix download of large files in Console

### PR DESCRIPTION
**Pull request by reivaj05**
Fixes: https://github.com/minio/console/issues/2760

### CODE REVIEW

**Comment by dvaldivia** [comment]
I found a memory problem while downloading a large file, to test this I did the following

1. Generate a `100GiB` file via `mkfile -n 100g ~/Desktop/LargeTestFile` (on macOS)
2. Upload the file via object browser, this completed just fine
3. attempt to download the file, then `Safari` reset the page due to memory pressure, but I saw the download continues even if the download progress component no longer reports it, after a few zombie connections, it stops al together
Screenshot 2023-04-12 at 11 41 37 AM

**Comment by dvaldivia** [comment]
perhaps for Safari we can force a direct download? @reivaj05

**Comment by reivaj05** [comment]
@dvaldivia I believe we won't be able to set anonymous access header if we force a direct download, is that right?

**Comment by dvaldivia** [comment]
@reivaj05 when do we need to do that? :S

**Comment by reivaj05** [comment]
Added way to download directly in safari if file size is more than 4G

**Review by bexsoft — CHANGES_REQUESTED** [review]
Tested the PR with the following scenarios:

- Uploaded 5GB File, everything OK
- Downloaded File in Chrome, Need to find a way to display more constant batches for the progress bar as it updates only every 25%

- On Safari, the whole application freezes between batches and sometimes crashes once the download has been completed

- On Firefox Navigator Download manager & MinIO's object manager opens at the same time (not really an issue as current behavior opens Firefox manager after MinIO's object manager completes the download)
-  On Opera same behavior as Firefox is observed

**Comment by cesnietor** [comment]
Tested  on Chrome with 4G and 100G files ✅ 
On Safari I also experienced the same behavior raised by @bexsoft  where the app crashes and kind of sends me to the Object browser page. This happens even with 4G files.  Small files seem to be working fine.

**Comment by reivaj05** [comment]
@bexsoft i couldn't find a better way to display progress, current approach to get the chunks is `fileSize/1.5G`, i could reduce the chunk size i9n the code but smaller chunks will translate in more requests to minio and rate limit errors, with 1.5G we avoid the rate limit error

@bexsoft @cesnietor i'm going to let safari browser handle the downloads directly instead of setting a limit because seems 4G files is still too much for safari to handle

**Comment by cesnietor** [comment]
Tested in Safari and is download is now being handled by the browser. ✅ 
Screenshot 2023-05-11 at 11 44 49 AM

**Review by cesnietor — DISMISSED** [review]
LGTM

**Review by cesnietor — APPROVED** [review]
typo fixed

**Pull request merged**
