### PR TITLE
Legal hold modal implementation

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

Implements Legal Hold modal

## How does it look?

Screen Shot 2020-11-23 at 13 29 24
Screen Shot 2020-11-23 at 13 29 19

### CODE REVIEW

**Review by cesnietor — COMMENTED** [review]
Screen Shot 2020-11-23 at 6 54 54 PM
if an error occurs the button save doesn't reset.

**Comment by bexsoft** [comment]
> Screen Shot 2020-11-23 at 6 54 54 PM
> 
> if an error occurs the button save doesn't reset.

Should be fixed now

**Review by cesnietor — DISMISSED** [review]

**Comment by kaankabalak** [comment]
Would it be possible to format the error message such that it is consistent with the rest of the error messages in the app?

Screen Shot 2020-11-24 at 11 08 28 AM

**Comment by bexsoft** [comment]
> Would it be possible to format the error message such that it is consistent with the rest of the error messages in the app?
> 
> Screen Shot 2020-11-24 at 11 08 28 AM

Added styles:

Screen Shot 2020-11-24 at 15 03 13

We will change all the error messages as mentioned in #99

**Review by kaankabalak — APPROVED** [review]

**Review by cesnietor — APPROVED** [review]

**Pull request merged**
