### PR TITLE
Fix regression on login path when using redirect url

### PR DESCRIPTION
**Pull request by cesnietor**
Fixes: https://github.com/minio/console/issues/3036

We changed the way of handling the errors in here https://github.com/minio/console/pull/3005 which caused a regression on the login path when using `MINIO_BROWSER_REDIRECT_URL` env variable.

### Test Steps
Please follow same steps as  https://github.com/minio/console/pull/2818
Note: Use correct command as explained in the comments like:
```
make build && CI=true MINIO_BROWSER_REDIRECT_URL=http://localhost:8000/console/subpath/ MINIO_SERVER_URL=http://localhost:9000 ./minio server --console-address ":9090" ~/Data
```

Go to http://localhost:8000/console/subpath/

It should redirect you to `http://localhost:8000/console/subpath/login` before it was redirecting to `http://localhost:8000/login`.

Other test:
- Login and then go to a different pat such as browser or access keys
- Delete the local storage for the page
- refresh the site, it should redirect you again to `http://localhost:8000/console/subpath/login`

### CODE REVIEW

**Comment by harshavardhana** [comment]
how do we make sure that this doesn't happen again? - can we add tests for this?

**Comment by cesnietor** [comment]
> how do we make sure that this doesn't happen again? - can we add tests for this?

I'll take a look @harshavardhana

**Comment by harshavardhana** [comment]
```
 ✖ RootUrl redirects to Login Page

   1) Failed to load the page at "http://localhost:8000/console/subpath".
      Increase the value of the "pageRequestTimeout" variable, enable the "retryTestPages" option, or use quarantine mode to perform additional attempts to execute this test.
      You can find troubleshooting information for this issue at "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".

      Error details:
      Error: ConnectionRefused

      Browser: Chrome 116.0.5845.140 / Ubuntu 22.04

         22 |
         23 |fixture("Tests using subpath").page(appBaseUrl);
         24 |
         25 |test("RootUrl redirects to Login Page", async (t) => {
         26 |  const loginButtonExists = elements.loginButton.exists;
       > 27 |  await t.navigateTo(rootUrl).expect(loginButtonExists).ok().wait(2000);
         28 |});
         29 |

         at <anonymous> (/home/runner/work/console/console/portal-ui/tests/subpath-nginx/test-unauthenticated-user.ts:27:11)
         at <anonymous> (/home/runner/work/console/console/portal-ui/tests/subpath-nginx/test-unauthenticated-user.ts:23:71)
         at __awaiter (/home/runner/work/console/console/portal-ui/tests/subpath-nginx/test-unauthenticated-user.ts:19:12)
         at <anonymous> (/home/runner/work/console/console/portal-ui/tests/subpath-nginx/test-unauthenticated-user.ts:25:53)

```

connection refused, looks like nginx is not running.

**Comment by cesnietor** [comment]
yes, @harshavardhana  I'm working on it :)

**Review by harshavardhana — APPROVED** [review]

**Comment by cesnietor** [comment]
fixed @harshavardhana  tests passing now.

**Review by harshavardhana — APPROVED** [review]

**Review by bexsoft — APPROVED** [review]

**Pull request merged**
