### PR TITLE
Fixed multiple issues on object browser upload

### LINKED ISSUE #1946: Upload directory with nested directories doesn't work correctly
I found that directory upload doesn't work correctly and result structure depends on file names.

### Test case 1
Upload _test_ folder with the following structure to _my_images_ bucket
```
test/aaa.jpeg
test/in_test/bbb.jpeg
```
gives/expected
```
my_images/test/aaa.jpeg
my_images/test/bbb.jpeg
-------------------------------
my_images/test/aaa.jpeg
my_images/test/in_test/bbb.jpeg
```

### Test case 2
Upload _test_ folder with the following structure to _my_images_ bucket
```
test/ccc.jpeg
test/in_test/bbb.jpeg
```
gives/expected
```
my_images/test/in_test/ccc.jpeg
my_images/test/in_test/bbb.jpeg
-------------------------------
my_images/test/ccc.jpeg
my_images/test/in_test/bbb.jpeg
```

### PR DESCRIPTION
**Pull request by bexsoft**
fixes #1946

## What does this do?

- Fixed issue with double slashes on upload manager
- Fixed sub folders not uploading in the correct subpaths location
- Fixed an issue upload when a file is already selected
- Fixed an issue with create path button with paths finished on slash
- Simplified path handling  for object browser

## How does it look?

Screen Shot 2022-05-04 at 22 13 47
Screen Shot 2022-05-04 at 22 14 53
Screen Shot 2022-05-04 at 22 14 08

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

### CODE REVIEW

**Comment by prakashsvmx** [comment]
Observations:
- nested folders are ignored and uploaded only at the top level. ( so same file name at nested folders results in overwrite)
-  Selecting an object and uploading a new file results in un expected upload (subsequent uploads also results in unexpected path)
image

image


Previously selected path and newly created prefix are appended  ( the path is not getting updated properly)

image

**Comment by bexsoft** [comment]
First issue with upload nested paths is solved (drag and drop component returns a different object for file. I added support for both as this was the issue I was seeing originally but with drag & drop)

Regarding the second issue, I'm still trying to replicate it (not able to yet)

**Comment by bexsoft** [comment]
Second issue was replicated. Fixed both of them

**Review by dvaldivia — APPROVED** [review]

**Comment by prakashsvmx** [comment]
there is an issue with Click on an object row -> Select (checkbox) of the Object -> Click on Create Path -> Enter a prefix -> upload an object - the result is  : the prefix disappears and the uploaded file as well.

**Comment by bexsoft** [comment]
> there is an issue with Click on an object row -> Select (checkbox) of the Object -> Click on Create Path -> Enter a prefix -> upload an object - the result is : the prefix disappears and the uploaded file as well.

Fixed

**Review by dvaldivia — APPROVED** [review]

**Review by jinapurapu — APPROVED** [review]
`hidePathButton={selectedObjects.length>0}`

**Pull request merged**
