### PR TITLE
fix: capacity reported usage value

### PR DESCRIPTION
**Pull request by harshavardhana**
do not use unix-epoch to be displayed, instead
use the actual value at that epoch to be displayed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
To test this PR 

```
$ gh pr checkout 2028
$ make assets && make install
$ CONSOLE_PROMETHEUS_URL=http://play.min.io:9091 CONSOLE_MINIO_REGION=us-east-1 CONSOLE_MINIO_SERVER=https://play.min.io:9000 console srv
```

**Comment by harshavardhana** [comment]
Also the display box is wrong, the value here is currently "free" space instead - its reporting it as `used space`

**Review by dvaldivia — APPROVED** [review]

**Review by prakashsvmx — APPROVED** [review]
LGTM :+1:

**Review by bexsoft — APPROVED** [review]
LGTM

**Pull request merged**
