### PR TITLE
Local bucket creation time

### PR DESCRIPTION
**Pull request by jinapurapu**
Screen Shot 2022-11-16 at 9 57 57 AM

Fixes https://github.com/minio/console/issues/2462

### CODE REVIEW

**Comment by kaankabalak** [comment]
Hi @jinapurapu, should we also apply the same change on the object browser while we're viewing the contents of the bucket too?

Screen Shot 2022-11-16 at 10 25 53 AM

**Comment by kaankabalak** [comment]
We might also want to consider introducing some padding between the Timezone and the Access fields too:

Screen Shot 2022-11-16 at 10 29 26 AM

**Review by kaankabalak — APPROVED** [review]
LGTM

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
@jinapurapu you should check this with object ModTime as well.

**Review by kaankabalak — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Review by reivaj05 — APPROVED** [review]

**Review by dvaldivia — APPROVED** [review]

**Pull request merged**
