### PR TITLE
Disabled Object Locking button when permissions are not set

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

Disabled object locking select when `s3:PutBucketObjectLockConfiguration` and `s3:PutBucketVersioning` permissions are not set.

This according create bucket specification: https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateBucket.html

## How does it look?

Screen Shot 2022-08-04 at 18 15 13
Screen Shot 2022-08-04 at 18 12 44

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

### CODE REVIEW

**Comment by jinapurapu** [comment]
Should retention also be disabled if the permissions aren't present? It is not disabled, and toggling it also toggles the Object Locking, but gives an error trying to submit
Screenshot from 2022-08-04 17-37-46
this is with the following permissions set
s3:ListAllMyBuckets
s3:CreateBucket
s3:GetBucketLocation
s3:GetObject

**Comment by bexsoft** [comment]
> Should retention also be disabled if the permissions aren't present? It is not disabled, and toggling it also toggles the Object Locking, but gives an error trying to submit Screenshot from 2022-08-04 17-37-46 this is with the following permissions set s3:ListAllMyBuckets s3:CreateBucket s3:GetBucketLocation s3:GetObject

Removed visibility of retention toggler when permissions are not available for object locking

**Comment by jinapurapu** [comment]
Retention is not visible for authorized users unless they select Versioning first. If this is desired behavior, it should be addressed in the help box. 
Screenshot from 2022-08-05 12-48-07
Screenshot from 2022-08-05 12-48-18

**Comment by bexsoft** [comment]
> Retention is not visible for authorized users unless they select Versioning first. If this is desired behavior, it should be addressed in the help box. Screenshot from 2022-08-05 12-48-07 Screenshot from 2022-08-05 12-48-18

Yes, that is the original behavior that we had, We can add that information in an upcoming PR

**Comment by harshavardhana** [comment]
Instead of showing 'Access Denied' it is better to a show nicer user friendly message contextually.

Not needed in this PR but it is something quite useful.

**Review by jinapurapu — DISMISSED** [review]

**Review by prakashsvmx — DISMISSED** [review]
Tested with the following policies:

Allow Policy
<details>

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:CreateBucket",
                "s3:DeleteBucket",
                "s3:ListBucket",
                "s3:PutBucketObjectLockConfiguration",
                "s3:PutBucketVersioning"
            ],
            "Resource": [
                "arn:aws:s3:::test*"
            ]
        }
    ]
}
```
</details>

Deny Policy
<details>

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:CreateBucket",
                "s3:DeleteBucket",
                "s3:ListBucket",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::test*"
            ]
        },
        {
            "Effect": "Deny",
            "Action": [
                "s3:PutBucketObjectLockConfiguration",
                "s3:PutBucketVersioning"
            ],
            "Resource": [
                "arn:aws:s3:::test*"
            ]
        }
    ]
}
```
</details>


@bexsoft 
User experience Observation:
The retention toggle controls the Locking.  ideally this should be the other way around.
i.e 
When locking Toggle is enabled, versioning and retention should be enabled automatically
When locking is disabled retention should be disabled.

**Review by cniackz — COMMENTED** [review]
Is the failure related to this PR?...

```
Found '/home/runner/work/console/console/.nvmrc' with version <17>
Now using node v1[7](https://github.com/minio/console/runs/7735178020?check_suite_focus=true#step:11:8).9.1 (npm v[8](https://github.com/minio/console/runs/7735178020?check_suite_focus=true#step:11:9).11.0)
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
warning "@emotion/react > @emotion/babel-plugin@11.[9](https://github.com/minio/console/runs/7735178020?check_suite_focus=true#step:11:10).2" has unmet peer dependency "@babel/core@^7.0.0".
warning "@emotion/react > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @mui/styles@5.8.0" has incorrect peer dependency "react@^17.0.0".
warning " > @uiw/react-textarea-code-editor@2.0.2" has unmet peer dependency "@babel/runtime@>=7.[10](https://github.com/minio/console/runs/7735178020?check_suite_focus=true#step:11:11).0".
warning " > kbar@0.1.0-beta.35" has incorrect peer dependency "react@^16.0.0 || ^17.0.0".
warning " > kbar@0.1.0-beta.35" has incorrect peer dependency "react-dom@^16.0.0 || ^17.0.0".
warning "kbar > @reach/portal@0.16.2" has incorrect peer dependency "react@^16.8.0 || 17.x".
warning "kbar > @reach/portal@0.16.2" has incorrect peer dependency "react-dom@^16.8.0 || 17.x".
warning "kbar > react-virtual@2.10.4" has incorrect peer dependency "react@^16.6.3 || ^17.0.0".
warning "kbar > @reach/portal > @reach/utils@0.16.0" has incorrect peer dependency "react@^16.8.0 || 17.x".
warning "kbar > @reach/portal > @reach/utils@0.16.0" has incorrect peer dependency "react-dom@^16.8.0 || 17.x".
warning " > react-chartjs-2@2.[11](https://github.com/minio/console/runs/7735178020?check_suite_focus=true#step:11:12).2" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0".
[3/4] Linking dependencies...
warning " > react-chartjs-2@2.11.2" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0".
warning " > react-moment@1.1.2" has unmet peer dependency "prop-types@^15.7.0".
warning " > react-virtualized@9.22.3" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha".
warning " > react-virtualized@9.22.3" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
warning " > react-window-infinite-loader@1.0.7" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha || ^17.0.0".
warning " > react-window-infinite-loader@1.0.7" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha || ^17.0.0".
warning " > recharts@2.1.10" has incorrect peer dependency "react@^16.0.0 || ^17.0.0".
warning " > recharts@2.1.10" has incorrect peer dependency "react-dom@^16.0.0 || ^17.0.0".
warning "recharts > react-resize-detector@6.7.8" has incorrect peer dependency "react@^16.0.0 || ^17.0.0".
warning "recharts > react-resize-detector@6.7.8" has incorrect peer dependency "react-dom@^16.0.0 || ^17.0.0".
warning "recharts > react-smooth@2.0.0" has unmet peer dependency "prop-types@^15.6.0".
warning "recharts > react-smooth@2.0.0" has incorrect peer dependency "react@^15.0.0 || ^16.0.0 || ^17.0.0".
warning "recharts > react-smooth@2.0.0" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0 || ^17.0.0".
warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".
warning "testcafe > testcafe-reporter-dashboard > io-ts@2.2.16" has unmet peer dependency "fp-ts@^2.5.0".
warning "testcafe > testcafe-reporter-dashboard > io-ts-types@0.5.16" has unmet peer dependency "fp-ts@^2.0.0".
warning "testcafe > testcafe-reporter-dashboard > monocle-ts@2.3.[13](https://github.com/minio/console/runs/7735178020?check_suite_focus=true#step:11:14)" has unmet peer dependency "fp-ts@^2.5.0".
warning "testcafe > testcafe-reporter-dashboard > newtype-ts@0.3.5" has unmet peer dependency "fp-ts@^2.0.0".
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
Done in 7.61s.
yarn run v1.22.[19](https://github.com/minio/console/runs/7735178020?check_suite_focus=true#step:11:20)
$ /home/runner/work/console/console/portal-ui/node_modules/.bin/prettier --check .
Checking formatting...
[warn] src/screens/Console/Buckets/ListBuckets/AddBucket/AddBucket.tsx
[warn] Code style issues found in the above file. Forgot to run Prettier?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by bexsoft** [comment]
> @bexsoft, Is the failure related to this PR?...
> 
> Test: `Workflow / React Code Has No Warnings & is Prettified, then Make Assets`
> 
> ```
> Found '/home/runner/work/console/console/.nvmrc' with version <17>
> Now using node v1[7](https://github.com/minio/console/runs/7735178020?check_suite_focus=true#step:11:8).9.1 (npm v[8](https://github.com/minio/console/runs/7735178020?check_suite_focus=true#step:11:9).11.0)
> yarn install v1.22.19
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> warning "@emotion/react > @emotion/babel-plugin@11.[9](https://github.com/minio/console/runs/7735178020?check_suite_focus=true#step:11:10).2" has unmet peer dependency "@babel/core@^7.0.0".
> warning "@emotion/react > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
> warning " > @mui/styles@5.8.0" has incorrect peer dependency "react@^17.0.0".
> warning " > @uiw/react-textarea-code-editor@2.0.2" has unmet peer dependency "@babel/runtime@>=7.[10](https://github.com/minio/console/runs/7735178020?check_suite_focus=true#step:11:11).0".
> warning " > kbar@0.1.0-beta.35" has incorrect peer dependency "react@^16.0.0 || ^17.0.0".
> warning " > kbar@0.1.0-beta.35" has incorrect peer dependency "react-dom@^16.0.0 || ^17.0.0".
> warning "kbar > @reach/portal@0.16.2" has incorrect peer dependency "react@^16.8.0 || 17.x".
> warning "kbar > @reach/portal@0.16.2" has incorrect peer dependency "react-dom@^16.8.0 || 17.x".
> warning "kbar > react-virtual@2.10.4" has incorrect peer dependency "react@^16.6.3 || ^17.0.0".
> warning "kbar > @reach/portal > @reach/utils@0.16.0" has incorrect peer dependency "react@^16.8.0 || 17.x".
> warning "kbar > @reach/portal > @reach/utils@0.16.0" has incorrect peer dependency "react-dom@^16.8.0 || 17.x".
> warning " > react-chartjs-2@2.[11](https://github.com/minio/console/runs/7735178020?check_suite_focus=true#step:11:12).2" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0".
> [3/4] Linking dependencies...
> warning " > react-chartjs-2@2.11.2" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0".
> warning " > react-moment@1.1.2" has unmet peer dependency "prop-types@^15.7.0".
> warning " > react-virtualized@9.22.3" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha".
> warning " > react-virtualized@9.22.3" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
> warning " > react-window-infinite-loader@1.0.7" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha || ^17.0.0".
> warning " > react-window-infinite-loader@1.0.7" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha || ^17.0.0".
> warning " > recharts@2.1.10" has incorrect peer dependency "react@^16.0.0 || ^17.0.0".
> warning " > recharts@2.1.10" has incorrect peer dependency "react-dom@^16.0.0 || ^17.0.0".
> warning "recharts > react-resize-detector@6.7.8" has incorrect peer dependency "react@^16.0.0 || ^17.0.0".
> warning "recharts > react-resize-detector@6.7.8" has incorrect peer dependency "react-dom@^16.0.0 || ^17.0.0".
> warning "recharts > react-smooth@2.0.0" has unmet peer dependency "prop-types@^15.6.0".
> warning "recharts > react-smooth@2.0.0" has incorrect peer dependency "react@^15.0.0 || ^16.0.0 || ^17.0.0".
> warning "recharts > react-smooth@2.0.0" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0 || ^17.0.0".
> warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
> warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".
> warning "testcafe > testcafe-reporter-dashboard > io-ts@2.2.16" has unmet peer dependency "fp-ts@^2.5.0".
> warning "testcafe > testcafe-reporter-dashboard > io-ts-types@0.5.16" has unmet peer dependency "fp-ts@^2.0.0".
> warning "testcafe > testcafe-reporter-dashboard > monocle-ts@2.3.[13](https://github.com/minio/console/runs/7735178020?check_suite_focus=true#step:11:14)" has unmet peer dependency "fp-ts@^2.5.0".
> warning "testcafe > testcafe-reporter-dashboard > newtype-ts@0.3.5" has unmet peer dependency "fp-ts@^2.0.0".
> warning Workspaces can only be enabled in private projects.
> [4/4] Building fresh packages...
> Done in 7.61s.
> yarn run v1.22.[19](https://github.com/minio/console/runs/7735178020?check_suite_focus=true#step:11:20)
> $ /home/runner/work/console/console/portal-ui/node_modules/.bin/prettier --check .
> Checking formatting...
> [warn] src/screens/Console/Buckets/ListBuckets/AddBucket/AddBucket.tsx
> [warn] Code style issues found in the above file. Forgot to run Prettier?
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> Error: Process completed with exit code 1.
> ```

Yes, a bad merge. Fixed

**Comment by jinapurapu** [comment]
Object Locking is not disabled and a bucket with Object Locking enabled can be created by a user with this policy, which does not include s3:PutBucketObjectLockConfiguration.
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:GetObject",
                "s3:ListAllMyBuckets",
                "s3:PutBucketVersioning",
                "s3:CreateBucket"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}`

**Comment by bexsoft** [comment]
> Object Locking is not disabled and a bucket with Object Locking enabled can be created by a user with this policy, which does not include s3:PutBucketObjectLockConfiguration. `{ "Version": "2012-10-17", "Statement": [ { "Effect": "Allow", "Action": [ "s3:GetBucketLocation", "s3:GetObject", "s3:ListAllMyBuckets", "s3:PutBucketVersioning", "s3:CreateBucket" ], "Resource": [ "arn:aws:s3:::*" ] } ] }`

We need another change from MinIO master for this, right now it will allow you to create them as there are no restrictions on that side. Need to review the `s3:PutBucketObjectLockConfiguration` case

**Comment by jinapurapu** [comment]
Using this policy without  "s3:PutBucketVersioning", I was able to create a versioned bucket with object locking, despite getting an error message
Screenshot from 2022-08-09 11-47-38
Screenshot from 2022-08-09 11-48-29
Screenshot from 2022-08-09 11-48-42
Screenshot from 2022-08-09 11-49-45
:

**Review by reivaj05 — APPROVED** [review]

**Review by Alevsk — APPROVED** [review]

**Pull request merged**
