### PR TITLE
Fixed an issue while deleting objects with similar prefixes

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

Fixed an issue while deleting all versions, where if there were two files with similar prefixes but you only wanted to delete one, both files got deleted

### Before
beforeff

### After
afterff

### CODE REVIEW

**Comment by harshavardhana** [comment]
We could also avoid doing Listing() if an "object" has been selected to delete, not sure why we are listing even in this case.

Listing is only needed if you are doing a directory delete. Can you explain why do we need to list() to DELETE ?

**Comment by bexsoft** [comment]
> We could also avoid doing Listing() if an "object" has been selected to delete, not sure why we are listing even in this case.
> 
> Listing is only needed if you are doing a directory delete. Can you explain why do we need to list() to DELETE ?

We are using this function to list all the versions of an object and delete them

**Review by dvaldivia — APPROVED** [review]

**Comment by harshavardhana** [comment]
> > We could also avoid doing Listing() if an "object" has been selected to delete, not sure why we are listing even in this case.
> > Listing is only needed if you are doing a directory delete. Can you explain why do we need to list() to DELETE ?
> 
> We are using this function to list all the versions of an object and delete them

So when all versions are not selected - are we not doing list() ?

**Comment by harshavardhana** [comment]
And what about unversioned bucket, where user selects do invoke delete all versions do we worry about listing at all ? Because there is no need to list since there is only one version.

**Comment by prakashsvmx** [comment]
@bexsoft 
Some prefixes are not getting deleted
<details>

I have set up a data like below:
```
➜ mc mb local22/test-bucket      
Bucket created successfully `local22/test-bucket`

 ➜ mc cp 1.txt local22/test-bucket/abc/abc 
 ➜ mc cp 1.txt local22/test-bucket/abc/abcd
 ➜ mc cp 1.txt local22/test-bucket/abc/1.txt

 ➜ mc version enable local22/test-bucket      

 ➜ mc cp 1.txt local22/test-bucket/versionabc/versionabc
 ➜ mc cp 1.txt local22/test-bucket/versionabc/versionabcdef
 ➜ mc cp 1.txt local22/test-bucket/versionabc/1.txt        
 ➜ mc cp 1.txt local22/test-bucket/abc/abcd       
 ➜ mc cp 1.txt local22/test-bucket/abc/abc 


➜ mc ls local22/test-bucket -r --versions           
[2023-09-07 10:54:14 IST]   117B STANDARD null v1 PUT abc/1.txt
[2023-09-07 10:55:37 IST]   117B STANDARD 6e417b58-e775-4cc3-b798-f6dc96b3fcbf v2 PUT abc/abc
[2023-09-07 10:54:05 IST]   117B STANDARD null v1 PUT abc/abc
[2023-09-07 10:55:36 IST]   117B STANDARD 77527e17-32ea-43fa-b3c4-3b9c5c9bba3b v2 PUT abc/abcd
[2023-09-07 10:54:10 IST]   117B STANDARD null v1 PUT abc/abcd
[2023-09-07 10:54:55 IST]   117B STANDARD 8afb1448-f037-491b-9cf0-d92ec9164d10 v1 PUT versionabc/1.txt
[2023-09-07 10:54:47 IST]   117B STANDARD 4b8d5213-fbe3-41e8-b6a6-b33146f3afe3 v1 PUT versionabc/versionabc
[2023-09-07 10:54:50 IST]   117B STANDARD 626437da-9a0c-43f0-aeef-f853f9aad0cf v1 PUT versionabc/versionabcdef

### Delete `abcd` prefix with versions from UI

 ➜ mc ls local22/test-bucket -r --versions
[2023-09-07 10:54:14 IST]   117B STANDARD null v1 PUT abc/1.txt
[2023-09-07 10:55:36 IST]   117B STANDARD 77527e17-32ea-43fa-b3c4-3b9c5c9bba3b v2 PUT abc/abcd
[2023-09-07 10:54:10 IST]   117B STANDARD null v1 PUT abc/abcd
[2023-09-07 10:54:55 IST]   117B STANDARD 8afb1448-f037-491b-9cf0-d92ec9164d10 v1 PUT versionabc/1.txt
[2023-09-07 10:54:47 IST]   117B STANDARD 4b8d5213-fbe3-41e8-b6a6-b33146f3afe3 v1 PUT versionabc/versionabc
[2023-09-07 10:54:50 IST]   117B STANDARD 626437da-9a0c-43f0-aeef-f853f9aad0cf v1 PUT versionabc/versionabcdef


Copy few more versions
➜ mc cp 1.txt local22/test-bucket/versionabc/versionabcdef
 ➜ mc cp 1.txt local22/test-bucket/versionabc/versionabc   


➜ mc ls local22/test-bucket -r --versions              
[2023-09-07 10:54:14 IST]   117B STANDARD null v1 PUT abc/1.txt
[2023-09-07 10:55:36 IST]   117B STANDARD 77527e17-32ea-43fa-b3c4-3b9c5c9bba3b v2 PUT abc/abcd
[2023-09-07 10:54:10 IST]   117B STANDARD null v1 PUT abc/abcd
[2023-09-07 10:54:55 IST]   117B STANDARD 8afb1448-f037-491b-9cf0-d92ec9164d10 v1 PUT versionabc/1.txt
[2023-09-07 10:56:59 IST]   117B STANDARD 4a73aa21-f890-49d5-9112-44f9d2e313fc v2 PUT versionabc/versionabc
[2023-09-07 10:54:47 IST]   117B STANDARD 4b8d5213-fbe3-41e8-b6a6-b33146f3afe3 v1 PUT versionabc/versionabc
[2023-09-07 10:56:56 IST]   117B STANDARD 6d73e398-3698-4d6c-aadc-13a5f7178e51 v2 PUT versionabc/versionabcdef
[2023-09-07 10:54:50 IST]   117B STANDARD 626437da-9a0c-43f0-aeef-f853f9aad0cf v1 PUT versionabc/versionabcdef

Trying to delete `versionabc` prefix from ui with versions option

➜ mc ls local22/test-bucket -r --versions
[2023-09-07 10:54:14 IST]   117B STANDARD null v1 PUT abc/1.txt
[2023-09-07 10:55:36 IST]   117B STANDARD 77527e17-32ea-43fa-b3c4-3b9c5c9bba3b v2 PUT abc/abcd
[2023-09-07 10:54:10 IST]   117B STANDARD null v1 PUT abc/abcd
[2023-09-07 10:54:55 IST]   117B STANDARD 8afb1448-f037-491b-9cf0-d92ec9164d10 v1 PUT versionabc/1.txt
[2023-09-07 10:56:56 IST]   117B STANDARD 6d73e398-3698-4d6c-aadc-13a5f7178e51 v2 PUT versionabc/versionabcdef
[2023-09-07 10:54:50 IST]   117B STANDARD 626437da-9a0c-43f0-aeef-f853f9aad0cf v1 PUT versionabc/versionabcdef

it is not deleted. 
![image](https://github.com/minio/console/assets/23444145/f166509f-f3bb-4425-9a64-7790af9788cc)

```
</details>


Note: Nothing in  Server Logs:

Trace
<details>

```
➜ mc admin trace local22 -v              
localhost:22000 [REQUEST s3.ListObjectVersions] [2023-09-07T11:14:30.219] [Client IP: 127.0.0.1]
localhost:22000 GET /test-bucket/?delimiter=&encoding-type=url&prefix=versionabc%2F&versions=
localhost:22000 Proto: HTTP/1.1
localhost:22000 Host: localhost:22000
localhost:22000 Authorization: AWS4-HMAC-SHA256 Credential=DCNL2QEAZ2QFMR55EZY7/20230907/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=5fa02f470b340e673d37b12edbaaa527bc86978e3d01cbfd8ce5e8d0e924da86
localhost:22000 Content-Length: 0
localhost:22000 User-Agent: MinIO (linux; amd64) minio-go/v7.0.58 MinIO Console/(dev)
localhost:22000 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost:22000 X-Amz-Date: 20230907T054430Z
localhost:22000 X-Amz-Security-Token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJEQ05MMlFFQVoyUUZNUjU1RVpZNyIsImV4cCI6MTY5NDEwNzUxMiwicGFyZW50IjoibWluaW8ifQ.8pb6t-XM0YH3e0SEiq26MlO5ocmcEGBWCc-_OvpnNsNPdnIHDBYNqf5si319aeUmbG5tYkSjRS2_-HMlRg_uPw
localhost:22000 
localhost:22000 [RESPONSE] [2023-09-07T11:14:30.220] [ Duration 642µs TTFB 626.73µs ↑ 98 B  ↓ 1.6 KiB ]
localhost:22000 200 OK
localhost:22000 Vary: Origin,Accept-Encoding
localhost:22000 X-Amz-Id-2: 48addc98c2360aa8669eaf51e6e422b59d52374e3af3dd7f59fd25b0da98e481
localhost:22000 X-Content-Type-Options: nosniff
localhost:22000 X-Amz-Request-Id: 17828791D2AFAD5D
localhost:22000 X-Xss-Protection: 1; mode=block
localhost:22000 Accept-Ranges: bytes
localhost:22000 Content-Length: 1618
localhost:22000 Content-Type: application/xml
localhost:22000 Server: MinIO
localhost:22000 Strict-Transport-Security: max-age=31536000; includeSubDomains
localhost:22000 <?xml version="1.0" encoding="UTF-8"?>
<ListVersionsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>test-bucket</Name><Prefix>versionabc/</Prefix><KeyMarker></KeyMarker><NextVersionIdMarker></NextVersionIdMarker><VersionIdMarker></VersionIdMarker><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated><Version><Key>versionabc/1.txt</Key><LastModified>2023-09-07T05:24:55.578Z</LastModified><ETag>&#34;4565d6ef17cf451513cd1b035abf1d4f&#34;</ETag><Size>117</Size><Owner><ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4</ID><DisplayName>minio</DisplayName></Owner><StorageClass>STANDARD</StorageClass><IsLatest>true</IsLatest><VersionId>8afb1448-f037-491b-9cf0-d92ec9164d10</VersionId></Version><Version><Key>versionabc/versionabcdef</Key><LastModified>2023-09-07T05:26:56.633Z</LastModified><ETag>&#34;4565d6ef17cf451513cd1b035abf1d4f&#34;</ETag><Size>117</Size><Owner><ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4</ID><DisplayName>minio</DisplayName></Owner><StorageClass>STANDARD</StorageClass><IsLatest>true</IsLatest><VersionId>6d73e398-3698-4d6c-aadc-13a5f7178e51</VersionId></Version><Version><Key>versionabc/versionabcdef</Key><LastModified>2023-09-07T05:24:50.774Z</LastModified><ETag>&#34;4565d6ef17cf451513cd1b035abf1d4f&#34;</ETag><Size>117</Size><Owner><ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4</ID><DisplayName>minio</DisplayName></Owner><StorageClass>STANDARD</StorageClass><IsLatest>false</IsLatest><VersionId>626437da-9a0c-43f0-aeef-f853f9aad0cf</VersionId></Version><EncodingType>url</EncodingType></ListVersionsResult>
localhost:22000 
localhost:22000 [REQUEST s3.ListObjectsV2] [2023-09-07T11:14:30.255] [Client IP: 127.0.0.1]
localhost:22000 GET /test-bucket/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=
localhost:22000 Proto: HTTP/1.1
localhost:22000 Host: localhost:22000
localhost:22000 User-Agent: MinIO (linux; amd64) minio-go/v7.0.58 MinIO Console/(dev)
localhost:22000 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost:22000 X-Amz-Date: 20230907T054430Z
localhost:22000 X-Amz-Security-Token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJEQ05MMlFFQVoyUUZNUjU1RVpZNyIsImV4cCI6MTY5NDEwNzUxMiwicGFyZW50IjoibWluaW8ifQ.8pb6t-XM0YH3e0SEiq26MlO5ocmcEGBWCc-_OvpnNsNPdnIHDBYNqf5si319aeUmbG5tYkSjRS2_-HMlRg_uPw
localhost:22000 X-Forwarded-For: 127.0.0.1
localhost:22000 Authorization: AWS4-HMAC-SHA256 Credential=DCNL2QEAZ2QFMR55EZY7/20230907/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=60e0a5eb4404f88a8558070fbdc087a3d1ebce939370432fd1045520c371f7c9
localhost:22000 Content-Length: 0
localhost:22000 
localhost:22000 [RESPONSE] [2023-09-07T11:14:30.256] [ Duration 502µs TTFB 488.516µs ↑ 114 B  ↓ 413 B ]
localhost:22000 200 OK
localhost:22000 Server: MinIO
localhost:22000 Vary: Origin,Accept-Encoding
localhost:22000 X-Amz-Id-2: 48addc98c2360aa8669eaf51e6e422b59d52374e3af3dd7f59fd25b0da98e481
localhost:22000 X-Amz-Request-Id: 17828791D4D77A0E
localhost:22000 X-Content-Type-Options: nosniff
localhost:22000 Accept-Ranges: bytes
localhost:22000 Content-Type: application/xml
localhost:22000 X-Xss-Protection: 1; mode=block
localhost:22000 Content-Length: 413
localhost:22000 Strict-Transport-Security: max-age=31536000; includeSubDomains
localhost:22000 <?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>test-bucket</Name><Prefix></Prefix><KeyCount>2</KeyCount><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><CommonPrefixes><Prefix>abc/</Prefix></CommonPrefixes><CommonPrefixes><Prefix>versionabc/</Prefix></CommonPrefixes><EncodingType>url</EncodingType></ListBucketResult>
localhost:22000 
localhost:22000 [REQUEST s3.GetBucketLocation] [2023-09-07T11:14:30.261] [Client IP: 127.0.0.1]
localhost:22000 GET /test-bucket/?location=
localhost:22000 Proto: HTTP/1.1
localhost:22000 Host: localhost:22000
localhost:22000 X-Amz-Date: 20230907T054430Z
localhost:22000 X-Amz-Security-Token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJEQ05MMlFFQVoyUUZNUjU1RVpZNyIsImV4cCI6MTY5NDEwNzUxMiwicGFyZW50IjoibWluaW8ifQ.8pb6t-XM0YH3e0SEiq26MlO5ocmcEGBWCc-_OvpnNsNPdnIHDBYNqf5si319aeUmbG5tYkSjRS2_-HMlRg_uPw
localhost:22000 X-Forwarded-For: 127.0.0.1
localhost:22000 Authorization: AWS4-HMAC-SHA256 Credential=DCNL2QEAZ2QFMR55EZY7/20230907/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=52a33277eea2ca3e01747140d9b3e86bec51d20618525d0ffa72dca9ba0cd15a
localhost:22000 Content-Length: 0
localhost:22000 User-Agent: MinIO (linux; amd64) minio-go/v7.0.58 MinIO Console/(dev)
localhost:22000 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost:22000 
localhost:22000 [RESPONSE] [2023-09-07T11:14:30.261] [ Duration 264µs TTFB 249.969µs ↑ 114 B  ↓ 128 B ]
localhost:22000 200 OK
localhost:22000 X-Content-Type-Options: nosniff
localhost:22000 X-Xss-Protection: 1; mode=block
localhost:22000 Content-Length: 128
localhost:22000 Content-Type: application/xml
localhost:22000 Strict-Transport-Security: max-age=31536000; includeSubDomains
localhost:22000 Vary: Origin,Accept-Encoding
localhost:22000 X-Amz-Request-Id: 17828791D5297881
localhost:22000 Accept-Ranges: bytes
localhost:22000 Server: MinIO
localhost:22000 X-Amz-Id-2: 48addc98c2360aa8669eaf51e6e422b59d52374e3af3dd7f59fd25b0da98e481
localhost:22000 <?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></LocationConstraint>
localhost:22000 
localhost:22000 [REQUEST s3.GetBucketPolicy] [2023-09-07T11:14:30.261] [Client IP: 127.0.0.1]
localhost:22000 GET /test-bucket/?policy=
localhost:22000 Proto: HTTP/1.1
localhost:22000 Host: localhost:22000
localhost:22000 X-Amz-Security-Token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJEQ05MMlFFQVoyUUZNUjU1RVpZNyIsImV4cCI6MTY5NDEwNzUxMiwicGFyZW50IjoibWluaW8ifQ.8pb6t-XM0YH3e0SEiq26MlO5ocmcEGBWCc-_OvpnNsNPdnIHDBYNqf5si319aeUmbG5tYkSjRS2_-HMlRg_uPw
localhost:22000 X-Forwarded-For: 127.0.0.1
localhost:22000 Authorization: AWS4-HMAC-SHA256 Credential=DCNL2QEAZ2QFMR55EZY7/20230907/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=b09a39f6ffcd6d9f953b1f4061110bd70fdcc53cf6e3c67909746f78f135cae4
localhost:22000 Content-Length: 0
localhost:22000 User-Agent: MinIO (linux; amd64) minio-go/v7.0.58 MinIO Console/(dev)
localhost:22000 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost:22000 X-Amz-Date: 20230907T054430Z
localhost:22000 
localhost:22000 [RESPONSE] [2023-09-07T11:14:30.261] [ Duration 209µs TTFB 196.482µs ↑ 114 B  ↓ 326 B ]
localhost:22000 404 Not Found
localhost:22000 Accept-Ranges: bytes
localhost:22000 Content-Type: application/xml
localhost:22000 X-Amz-Id-2: 48addc98c2360aa8669eaf51e6e422b59d52374e3af3dd7f59fd25b0da98e481
localhost:22000 X-Amz-Request-Id: 17828791D5321EE7
localhost:22000 Content-Length: 326
localhost:22000 Server: MinIO
localhost:22000 Strict-Transport-Security: max-age=31536000; includeSubDomains
localhost:22000 Vary: Origin,Accept-Encoding
localhost:22000 X-Content-Type-Options: nosniff
localhost:22000 X-Xss-Protection: 1; mode=block
localhost:22000 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucketPolicy</Code><Message>The bucket policy does not exist</Message><BucketName>test-bucket</BucketName><Resource>/test-bucket/</Resource><RequestId>17828791D5321EE7</RequestId><HostId>48addc98c2360aa8669eaf51e6e422b59d52374e3af3dd7f59fd25b0da98e481</HostId></Error>
localhost:22000 
localhost:22000 [REQUEST s3.GetBucketTagging] [2023-09-07T11:14:30.262] [Client IP: 127.0.0.1]
localhost:22000 GET /test-bucket/?tagging=
localhost:22000 Proto: HTTP/1.1
localhost:22000 Host: localhost:22000
localhost:22000 X-Amz-Security-Token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJEQ05MMlFFQVoyUUZNUjU1RVpZNyIsImV4cCI6MTY5NDEwNzUxMiwicGFyZW50IjoibWluaW8ifQ.8pb6t-XM0YH3e0SEiq26MlO5ocmcEGBWCc-_OvpnNsNPdnIHDBYNqf5si319aeUmbG5tYkSjRS2_-HMlRg_uPw
localhost:22000 X-Forwarded-For: 127.0.0.1
localhost:22000 Authorization: AWS4-HMAC-SHA256 Credential=DCNL2QEAZ2QFMR55EZY7/20230907/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=49b1097f287337f541aeb42bf802d0d7c43a71275e68f2027f629d81e615a45b
localhost:22000 Content-Length: 0
localhost:22000 User-Agent: MinIO (linux; amd64) minio-go/v7.0.58 MinIO Console/(dev)
localhost:22000 X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
localhost:22000 X-Amz-Date: 20230907T054430Z
localhost:22000 
localhost:22000 [RESPONSE] [2023-09-07T11:14:30.262] [ Duration 97µs TTFB 89.58µs ↑ 114 B  ↓ 313 B ]
localhost:22000 404 Not Found
localhost:22000 Accept-Ranges: bytes
localhost:22000 Content-Length: 313
localhost:22000 Strict-Transport-Security: max-age=31536000; includeSubDomains
localhost:22000 X-Amz-Id-2: 48addc98c2360aa8669eaf51e6e422b59d52374e3af3dd7f59fd25b0da98e481
localhost:22000 X-Content-Type-Options: nosniff
localhost:22000 X-Xss-Protection: 1; mode=block
localhost:22000 Content-Type: application/xml
localhost:22000 Server: MinIO
localhost:22000 Vary: Origin,Accept-Encoding
localhost:22000 X-Amz-Request-Id: 17828791D5391750
localhost:22000 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchTagSet</Code><Message>The TagSet does not exist</Message><BucketName>test-bucket</BucketName><Resource>/test-bucket/</Resource><RequestId>17828791D5391750</RequestId><HostId>48addc98c2360aa8669eaf51e6e422b59d52374e3af3dd7f59fd25b0da98e481</HostId></Error>
localhost:22000 
```

</details>

**Comment by bexsoft** [comment]
> And what about unversioned bucket, where user selects do invoke delete all versions do we worry about listing at all ? Because there is no need to list since there is only one version.

That's correct we have a separated clause for this case, we just list in case we want to delete multiple versions of an object. This is also the behavior we observed in mc

**Comment by bexsoft** [comment]
> @bexsoft Some prefixes are not getting deleted
> 
> Note: Nothing in Server Logs:
> 
> Trace

Let me try to replicate this, one question when you are referring to `versionabc` are you trying to delete the folder or just the files?

Thank you in advance

**Comment by prakashsvmx** [comment]
I was trying to delete prefix @bexsoft

**Comment by bexsoft** [comment]
> https://github.com/minio/console/assets/23444145/f166509f-f3bb-4425-9a64-7790af9788cc

I reproduced the issue and sent a fix for it. Can you please help me to test again @prakashsvmx ? 
Thank you in advance.

**Review by cesnietor — APPROVED** [review]

**Review by prakashsvmx — APPROVED** [review]
LGTM

**Pull request merged**
