### PR TITLE
Fix download of folders

### PR DESCRIPTION
**Pull request by reivaj05**
Fixes: https://github.com/minio/console/issues/2890

Folders don't have a size attribute when they are retrieved from minio, i believe this is for design so new way to download in chunks won't work in this case, for the moment i'll let the browser handle the download as we do it for safari and later i'll check minio code if there is a way to send the size for folders to console

### CODE REVIEW

**Review by cesnietor — APPROVED** [review]
Tested LGTM, thanks for the fix.

**Comment by cesnietor** [comment]
@reivaj05  I just noticed that on Chrome the snackBar message doesn't show up like it does on Safari when downloading the folder.

**Comment by reivaj05** [comment]
@cesnietor That's right, it doesn't show as in Safari, i was't sure if we want to display it in this case, Safari always downloads with the browser so we display the message all the time, it can be added if we want the same behavior for this case

cc: @dvaldivia

**Comment by cesnietor** [comment]
@reivaj05  yeah it indeed might not be needed since Chrome has a more visible indication on what's going on.
Screenshot 2023-06-16 at 2 24 49 PM

**Review by dvaldivia — APPROVED** [review]

**Review by kaankabalak — APPROVED** [review]

**Review by prakashsvmx — APPROVED** [review]

**Review by bexsoft — APPROVED** [review]

**Pull request merged**
