### PR TITLE
Fix Kbar in operator mode

### PR DESCRIPTION
**Pull request by dvaldivia**
Screen Shot 2022-02-28 at 10 01 47 PM

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

**Comment by prakashsvmx** [comment]
Observation:
do we apply permissions while listing the actions for users with policy?
e.g : User with policy which denies admin actions. (users, groups etc... are not expected as they would redirect to bucket page when clicked because of policy)

image

**Comment by dvaldivia** [comment]
@prakashsvmx aaah, we need to deal with this problem, right now we load the kbar option once and don't reload after the session is loaded (when we get the right access policy) so we would need to introduce something to re-evaluate the kbar menu after we get the access policy to avoid listing these

**Review by prakashsvmx — APPROVED** [review]
Tested. Changes look good to me. We can improve progressively

**Review by Alevsk — APPROVED** [review]

**Review by bexsoft — APPROVED** [review]
LGTM

**Pull request merged**
