### PR TITLE
Tests for Object delete button on SideBar

### PR DESCRIPTION
**Pull request by Alevsk**

### CODE REVIEW

**Comment by Alevsk** [comment]
The tests are failing because this relies on compiling the latest assets, if you test this directly against port 5005, should work

**Comment by dvaldivia** [comment]
@Alevsk assets get auto generated on every PR

**Comment by dvaldivia** [comment]
tests fail since they assume the existence of a file called `test.txt` but each test should upload the file, ideally the file name should be unique to the test so they can run concurrently

**Review by cniackz — APPROVED** [review]
LGTM

**Review by adfost — APPROVED** [review]

**Pull request merged**
