### PR TITLE
access keys ui details improvement and edit

### LINKED ISSUE #3133: There is no way to  add or edit `expire time`/`name` /`description` when i craete `Access Keys`
* Install method: docker compose
* minio version: RELEASE.2023-11-20T22-40-07Z

When i create access key, there is no way to add or edit fileds like `expiry`/`name`/`description`.
And i had search in docs from your website to find how to resolve it.
I can only find use command in console and i can not login into my console.

Would you plan to add some ways to add or edit them in UI ?Thanks a lot.

image
image

### PR DESCRIPTION
**Pull request by prakashsvmx**
access keys ui details improvement and edit
Adds Ability to add/edit expiry and other editable fields.

Fixes https://github.com/minio/console/issues/3064
Fixes #3133
<summary> How does it look </summary>

<details>

image

image

image

image

User specific

image

image

</details>

### CODE REVIEW

**Comment by prakashsvmx** [comment]
@bexsoft  `make swagger-gen` affected more files. is anything missed or changed recently ?

**Comment by bexsoft** [comment]
> @bexsoft `make swagger-gen` affected more files. is anything missed or changed recently ?

Swagger version was updated a couple of PRs back, you'll need to upgrade to latest

**Review by bexsoft — APPROVED** [review]
LGTM, Just small style adjustments needed, will be changed later

**Review by cesnietor — APPROVED** [review]
Thanks for adding tests.
Can we make it next time the BE and UI changes in separate PRs? so that they are easier to review? thank you!!

**Comment by jinapurapu** [comment]
Can the comments be viewed/edited?

**Comment by prakashsvmx** [comment]
@cesnietor  `make swagger-gen` also  updates typescript api file.  So I will check for the best approach next time.

**Comment by prakashsvmx** [comment]
@jinapurapu the upstream api does not have an option to update comments. We can check and update later when it supports.

**Pull request merged**
