### PR TITLE
Service Account Policy API

### PR DESCRIPTION
**Pull request by adfost**
API to get service account policy: http://localhost:9090/api/v1/service-accounts/{service-account-name}/policy

### CODE REVIEW

**Review by dvaldivia — CHANGES_REQUESTED** [review]
Please rebase and regen swagger stubs

**Review by prakashsvmx — DISMISSED** [review]
Verified the api response for a service account which has a policy attached. :+1:

**Review by cniackz — DISMISSED** [review]

**Review by dvaldivia — CHANGES_REQUESTED** [review]
Can you add an integration test under `/integration/service_accounts_test.go` testing this API

**Comment by cniackz** [comment]
Thank @dvaldivia for pointing out on the creation of the test for this end point.
Also we need to make sure `Go / Checking Lint` is passing to approve this PR.

**Review by prakashsvmx — APPROVED** [review]
LGTM

**Review by dvaldivia — APPROVED** [review]

**Pull request merged**
