### PR TITLE
UX license logo on sidebar

### PR DESCRIPTION
**Pull request by prakashsvmx**
License logo on sidebar

Fixes https://github.com/miniohq/engineering/issues/854

<summary> How does it look </summary>

<details>

image

image

image

</details>

### CODE REVIEW

**Review by oscarocastellanos — APPROVED** [review]
LGTM

**Review by jinapurapu — APPROVED** [review]

**Comment by cniackz** [comment]
Locally tested: 

Screen Shot 2022-05-27 at 5 15 49 PM

**Review by cniackz — APPROVED** [review]
LGTM

**Comment by cniackz** [comment]
AGPL Free Software, nice! 👍

**Comment by oscarocastellanos** [comment]
> AGPL Free Software, nice! 👍

We gotta keep it real!

**Review by bexsoft — APPROVED** [review]

**Pull request merged**
