### PR TITLE
Remove unused components

### PR DESCRIPTION
**Pull request by dvaldivia**
All these are components that exist and no one imports 

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

**Review by dilverse — APPROVED** [review]

**Review by pjuarezd — APPROVED** [review]

**Review by kaankabalak — APPROVED** [review]
LGTM

**Review by jinapurapu — APPROVED** [review]

**Comment by allanrogerr** [comment]
@dvaldivia Conflicting files
portal-ui/src/screens/Console/Support/RegisterStatus.tsx

**Review by allanrogerr — CHANGES_REQUESTED** [review]
Why is there a conflict on portal-ui/src/screens/Console/Support/RegisterStatus.tsx?

**Comment by dvaldivia** [comment]
rebased, @allanrogerr

**Comment by allanrogerr** [comment]
I am trying to figure out why Operator API tests keep failing... @dvaldivia

**Comment by dvaldivia** [comment]
@allanrogerr it's unrelated to this change, they are failing for other PRs, but if you find the root cause that'd be amazing xD

**Review by bexsoft — APPROVED** [review]
LGTM

**Review by allanrogerr — APPROVED** [review]

**Review by prakashsvmx — APPROVED** [review]

**Pull request merged**
