### PR TITLE
remove remaining variable references for mcs

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by cesnietor** [comment]
Lol this I also thought was necessary but the MCS3Client there reflects the `mc`  S3 client definition is just to call mc functions.
So not needed XD.

**Comment by harshavardhana** [comment]
> Lol this I also thought was necessary but the MCS3Client there reflects the `mc` S3 client definition, is just to call mc functions.
> So not needed XD.

is it necessary to call it `mc` S3 client?

**Comment by cesnietor** [comment]
> is it necessary to call it mc S3 client?
mmh well it is that, any suggestions? probably minioClient?

**Comment by harshavardhana** [comment]
To avoid the confusion moved to `mcClient` instead of `mcS3Client`

**Pull request merged**
