### PR TITLE
UX Inspect screen

### PR DESCRIPTION
**Pull request by prakashsvmx**
UX Inspect screen

Closes #https://github.com/miniohq/engineering/issues/550

How does it look:
image

Responsive
image

### CODE REVIEW

**Comment by cniackz** [comment]
There is a console warning when we click `inspect` as shown below:
https://user-images.githubusercontent.com/6667358/158278668-cffd42e5-39ce-475f-8836-be60327d3890.mov

**Review by cniackz — CHANGES_REQUESTED** [review]
Hello @prakashsvmx 

There is a console warning when we click `inspect` as shown below:
https://user-images.githubusercontent.com/6667358/158278668-cffd42e5-39ce-475f-8836-be60327d3890.mov
Log attached below:
[console-warning.log](https://github.com/minio/console/files/8249091/console-warning.log)

# Warning
```js
react_devtools_backend.js:3973 Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
```

This was introduced in this PR, tested for same behavior in main branch, and `warning` does not show up.

Please help us to avoid this warning, thank you! 👍

**Comment by prakashsvmx** [comment]
@oscarocastellanos  @cniackz Thank you. I have updated . PTAL.

**Review by oscarocastellanos — APPROVED** [review]
LGTM

**Review by bexsoft — APPROVED** [review]

**Comment by prakashsvmx** [comment]
@jinapurapu  
>Should there be a notification if the requested Inspect doesn't match an existing path? It downloads a blank zip file with no indication that anything went wrong

i have not found any error handling in such scenarios. may be that is expected. More on API PR https://github.com/minio/console/pull/1540#issuecomment-1035543502

**Review by dvaldivia — APPROVED** [review]

**Pull request merged**
