### PR TITLE
Initial Tools Pages Migrations

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

Migrates the following pages to mds:

- Call Home
- Inspect
- Profile
- Health

## How does it look?
Screenshot 2023-08-02 at 18 23 21
Screenshot 2023-08-02 at 18 23 15
Screenshot 2023-08-02 at 18 23 10
Screenshot 2023-08-02 at 18 23 04

### CODE REVIEW

**Comment by cesnietor** [comment]
Screenshot 2023-08-03 at 11 09 12 AM
Screenshot 2023-08-03 at 11 09 04 AM
Button `Save Configuration` in Call Home  looks disable but it's still clickable and when clicked it calls and returns a 500

**Comment by cesnietor** [comment]
Inspect redirects you to register your closer if you haven't registered when you fill the data and click `Inspect` is that expected? It's not clear that the feature is only available if the cluster is registered.

**Comment by bexsoft** [comment]
> Inspect redirects you to register your closer if you haven't registered when you fill the data and click `Inspect` is that expected? It's not clear that the feature is only available if the cluster is registered.
> 
> Same for Profile

Yes it is expected, there is a note at the top of the page asking to register your cluster

**Comment by bexsoft** [comment]
> Screenshot 2023-08-03 at 11 09 12 AM Screenshot 2023-08-03 at 11 09 04 AM Button `Save Configuration` in Call Home looks disable but it's still clickable and when clicked it calls and returns a 500

This should redirect you to Register your cluster as well

**Review by cesnietor — APPROVED** [review]
As discussed internally the features that require cluster registration should be disabled completely so that it's clear that they need to register the cluster. We can either merge this change for now since that is the current behavior and add as an improvement in another one or fix here.

**Review by pjuarezd — APPROVED** [review]

**Pull request merged**
