### PR TITLE
Set Operator Logo for Operator Mode

### LINKED ISSUE #406: New Operator Console logo

### PR DESCRIPTION
**Pull request by dvaldivia**
Screen Shot 2020-12-10 at 3 45 03 PM

fixes #406

### CODE REVIEW

**Comment by belvid** [comment]
For some reason it looks pixelated. I will give later a better version of the logo.

**Comment by dvaldivia** [comment]
I used the SVG version of the logo @belvid

**Comment by belvid** [comment]
Can you send a screenshot of the the whole window to check the logo in context?

**Comment by dvaldivia** [comment]
Screen Shot 2020-12-10 at 5 16 11 PM
@belvid

**Review by belvid — APPROVED** [review]
Looks good to me!

**Review by bexsoft — CHANGES_REQUESTED** [review]
Functionality is fine but logo looks weird, seems like it has been cutted off from the bottom side (Observe the O characters)

Screen Shot 2020-12-10 at 22 58 50
Screen Shot 2020-12-10 at 22 58 13

**Review by bexsoft — APPROVED** [review]
Functionality will be send as it is right now, will update in future PR

**Review by kaankabalak — APPROVED** [review]

**Pull request merged**
