### PR TITLE
Add Tenant page refactor

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

Refactored add tenant page to be working with reducers & settings styles

## How does it look?

Screen Shot 2021-03-01 at 17 17 48
Screen Shot 2021-03-01 at 17 17 39
Screen Shot 2021-03-01 at 17 17 27
Screen Shot 2021-03-01 at 17 17 17
Screen Shot 2021-03-01 at 17 17 11

### CODE REVIEW

**Review by dvaldivia — APPROVED** [review]

**Review by dvaldivia — DISMISSED** [review]

**Review by Alevsk — CHANGES_REQUESTED** [review]
files uploaded are not sent as base64 encoded strings, that's preventing the tenants to de deployed

**Comment by cesnietor** [comment]
It's a minor comment but if I do the window shorter the text of `How would you like to name this new tenant?`
 stays there
 Screen Shot 2021-03-02 at 7 54 32 PM

**Comment by cesnietor** [comment]
LGTM

**Review by cesnietor — APPROVED** [review]

**Review by Alevsk — APPROVED** [review]
Tested, works for deploying tenant with encryption and TLS enabled

**Pull request merged**
