### PR TITLE
Changed Styles & some routes for console menu

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

- Changed styles for menu
- Changed Settings page title
- Changed Service Account option to be Access Keys
- Changed all Service Accounts labels to be Access keys in console (Operator is not included in this change)

**NOTE:** This is first stage for this change, Logo will be changed once mds application logo component is created

## How does it look?

Screenshot 2022-11-04 at 21 57 04
Screenshot 2022-11-04 at 21 56 59
Screenshot 2022-11-04 at 21 56 41
Screenshot 2022-11-04 at 21 56 37
Screenshot 2022-11-04 at 21 56 29

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

### CODE REVIEW

**Comment by kaankabalak** [comment]
Hi @bexsoft, as we have changed the name of the `Service Accounts` page to `Access Keys`, are we planning to update the `Service Accounts` page such that we mention `Access Keys` instead? It might be confusing for the user to click on a page called `Access Keys` and not see mentions of it when navigated.

Screen Shot 2022-11-07 at 2 30 56 PM

**Review by oscarocastellanos — APPROVED** [review]
lgtm

**Comment by bexsoft** [comment]
> Hi @bexsoft, as we have changed the name of the `Service Accounts` page to `Access Keys`, are we planning to update the `Service Accounts` page such that we mention `Access Keys` instead? It might be confusing for the user to click on a page called `Access Keys` and not see mentions of it when navigated.
> 
> Screen Shot 2022-11-07 at 2 30 56 PM

Hi @kaankabalak!

In this case, it is called access keys as it includes service accounts & change password features, I agree we need to discuss this, meanwhile I changed the section title only so users won't get confused thinking link is redirecting them to another page.

**Comment by bexsoft** [comment]
> > Hi @bexsoft, as we have changed the name of the `Service Accounts` page to `Access Keys`, are we planning to update the `Service Accounts` page such that we mention `Access Keys` instead? It might be confusing for the user to click on a page called `Access Keys` and not see mentions of it when navigated.
> > Screen Shot 2022-11-07 at 2 30 56 PM
> 
> Hi @kaankabalak!
> 
> In this case, it is called access keys as it includes service accounts & change password features, I agree we need to discuss this, meanwhile I changed the section title only so users won't get confused thinking link is redirecting them to another page.

Changing all Service accounts labels to Access Keys in console as agreed in the meeting

**Review by reivaj05 — APPROVED** [review]

**Review by dvaldivia — APPROVED** [review]

**Pull request merged**
