### PR TITLE
Add test for listing an object

### PR DESCRIPTION
**Pull request by cniackz**
Fixes miniohq/engineering#379

Test for `List Objects` end point.

### CODE REVIEW

**Review by bexsoft — APPROVED** [review]

**Comment by prakashsvmx** [comment]
@cniackz Please address the conflicts.

**Review by prakashsvmx — APPROVED** [review]
LGTM.

**Review by adfost — APPROVED** [review]

**Comment by kaankabalak** [comment]
@cniackz, could you take a look at the conflict on `integration/buckets_test.go` please?

**Review by kaankabalak — APPROVED** [review]

**Review by dvaldivia — APPROVED** [review]

**Review by bexsoft — APPROVED** [review]
LGTM

**Pull request merged**
