### PR TITLE
Fix Node Number validation

### PR DESCRIPTION
**Pull request by dvaldivia**
Fixes the validation of nodes to cover the following situations 

### Less than 4 nodes (not allowed)
Screen Shot 2021-08-02 at 1 50 34 PM

### Not enough schedulable nodes in the cluster 
Screen Shot 2021-08-02 at 1 50 49 PM

### Not enough worker nodes in the cluster
Screen Shot 2021-08-02 at 2 03 05 PM
7097-45d1-9b77-6f1a8572a212.png">

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

**Review by adfost — APPROVED** [review]
LGTM

**Review by bexsoft — CHANGES_REQUESTED** [review]
There is an error flashing during tenant size screen first render

**Comment by dvaldivia** [comment]
@bexsoft I swear it was that way when I found it officer 

This is on `v0.8.1`

ezgif-7-ae434dadeff7

**Comment by bexsoft** [comment]
> @bexsoft I swear it was that way when I found it officer
> 
> This is on `v0.8.1`
> 
> ezgif-7-ae434dadeff7

I see, then we will need to file a new bug for it please

**Review by bexsoft — APPROVED** [review]
LGTM, a new ticket will be fixed for the flashing issue

**Comment by bexsoft** [comment]
Ticket https://github.com/minio/console/issues/921 created for missing issue

**Pull request merged**
