### PR TITLE
Remove redundant path from Tools

### PR DESCRIPTION
**Pull request by kaankabalak**

### CODE REVIEW

**Comment by kaankabalak** [comment]
We have duplicate paths on lines 38 and 67 of portal-ui/src/screens/Console/Tools/Tools.tsx, so the redundant path has been removed

**Comment by cniackz** [comment]
It looks good to me:

Screen Shot 2022-04-21 at 7 02 56 PM

**Review by cniackz — APPROVED** [review]
LGTM

**Review by bexsoft — APPROVED** [review]
I think IAM_PAGES.TOOLS_WATCH can be removed too. it can be removed in another PR

**Pull request merged**
