### PR TITLE
Fix inconsistencies in Health Diagnostics UI

### PR DESCRIPTION
**Pull request by kaankabalak**
Fixes https://github.com/miniohq/engineering/issues/492
Fixes https://github.com/miniohq/engineering/issues/495

### CODE REVIEW

**Comment by kaankabalak** [comment]
The check that is failing seems to be the Operator UI test, specifically the following, which is unrelated with this PR:
```
✖ Test Prometheus config fields can be edited and submitted

   1) The specified selector does not match any element in the DOM tree.

       > | Selector('#prometheus_image')

      Browser: Chrome 104.0.5112.79 / Linux 0.0

         131 |    .ok();
         132 |};
         133 |export const checkMonitoringFieldsAcceptValues = async (tenantName: string) => {
         134 |  await goToMonitoringSection(tenantName);
         1[35](https://github.com/minio/console/runs/7757633068?check_suite_focus=true#step:12:36) |  await t
       > 1[36](https://github.com/minio/console/runs/7757633068?check_suite_focus=true#step:12:37) |    .typeText("#prometheus_image", "quay.io/prometheus/prometheus:latest", {
         1[37](https://github.com/minio/console/runs/7757633068?check_suite_focus=true#step:12:38) |      replace: true,
         1[38](https://github.com/minio/console/runs/7757633068?check_suite_focus=true#step:12:39) |    })
         1[39](https://github.com/minio/console/runs/7757633068?check_suite_focus=true#step:12:40) |    .typeText("#sidecarImage", "library/alpine:latest", { replace: true })
         1[40](https://github.com/minio/console/runs/7757633068?check_suite_focus=true#step:12:41) |    .typeText("#initImage", "library/busybox:1.33.1", { replace: true })
         1[41](https://github.com/minio/console/runs/7757633068?check_suite_focus=true#step:12:42) |    .typeText("#diskCapacityGB", "1", { replace: true })

         at <anonymous> (/home/runner/work/console/console/portal-ui/tests/operator/tenants.ts:136:6)
         at fulfilled (/home/runner/work/console/console/portal-ui/tests/operator/tenants.ts:20:58)
```

**Review by bexsoft — APPROVED** [review]

**Comment by cniackz** [comment]
Tried testing this PR, but all I get is the same error:

Screen Shot 2022-08-12 at 12 06 15 PM

And in the logs I see this:

```
$ ~/go/bin/console server
Serving console at http://[::]:9090
ErrorWithContext:license not found

ErrorWithContext:license not found

ErrorWithContext:websocket: request origin not allowed by Upgrader.CheckOrigin

ErrorWithContext:websocket: request origin not allowed by Upgrader.CheckOrigin

ErrorWithContext:websocket: request origin not allowed by Upgrader.CheckOrigin

ErrorWithContext:license not found

ErrorWithContext:license not found

ErrorWithContext:websocket: request origin not allowed by Upgrader.CheckOrigin
```

@kaankabalak is there a way to test this without that WebSocket issue?. 
Should I register my cluster in Subnet to get this feature working?...
Just trying to understand how I can test this.
Thanks!

**Review by cniackz — COMMENTED** [review]
Tried testing this PR, but all I get is the same error:

Screen Shot 2022-08-12 at 12 06 15 PM

And in the logs I see this:

```
$ ~/go/bin/console server
Serving console at http://[::]:9090
ErrorWithContext:license not found

ErrorWithContext:license not found

ErrorWithContext:websocket: request origin not allowed by Upgrader.CheckOrigin

ErrorWithContext:websocket: request origin not allowed by Upgrader.CheckOrigin

ErrorWithContext:websocket: request origin not allowed by Upgrader.CheckOrigin

ErrorWithContext:license not found

ErrorWithContext:license not found

ErrorWithContext:websocket: request origin not allowed by Upgrader.CheckOrigin
```

@kaankabalak is there a way to test this without that WebSocket issue?. 
Should I register my cluster in Subnet to get this feature working?...
Just trying to understand how I can test this.
Thanks!

**Comment by kaankabalak** [comment]
> @kaankabalak is there a way to test this without that WebSocket issue?. Should I register my cluster in Subnet to get this feature working?... Just trying to understand how I can test this. Thanks!

@cniackz, I think this is a known issue for WebSocket related features, could you please try testing this on port 9090 please?

**Comment by bexsoft** [comment]
> Tried testing this PR, but all I get is the same error:
> 
> Screen Shot 2022-08-12 at 12 06 15 PM
> 
> And in the logs I see this:
> 
> ```
> $ ~/go/bin/console server
> Serving console at http://[::]:9090
> ErrorWithContext:license not found
> 
> ErrorWithContext:license not found
> 
> ErrorWithContext:websocket: request origin not allowed by Upgrader.CheckOrigin
> 
> ErrorWithContext:websocket: request origin not allowed by Upgrader.CheckOrigin
> 
> ErrorWithContext:websocket: request origin not allowed by Upgrader.CheckOrigin
> 
> ErrorWithContext:license not found
> 
> ErrorWithContext:license not found
> 
> ErrorWithContext:websocket: request origin not allowed by Upgrader.CheckOrigin
> ```
> 
> @kaankabalak is there a way to test this without that WebSocket issue?. Should I register my cluster in Subnet to get this feature working?... Just trying to understand how I can test this. Thanks!

You need to test on 9090, websockets are disabled for 5005. Don't forget to make assets first

**Comment by cniackz** [comment]
@kaankabalak please ignore my previous note. I see things working if I test UI changes over port 9090 with the steps you provided to me. Will note that those steps and this looks good to me

**Review by cniackz — APPROVED** [review]
LGTM

**Review by reivaj05 — APPROVED** [review]

**Pull request merged**
