### PR TITLE
Improve Tier status accessibility 

### PR DESCRIPTION
**Pull request by jinapurapu**
Screen Shot 2022-10-25 at 11 54 03 AM

### CODE REVIEW

**Review by djwfyi — APPROVED** [review]
Just two icons? Online and offline?
This icons offer a much better way to distinguish for those who cannot rely on color alone.

Looks good to me.

**Review by reivaj05 — APPROVED** [review]

**Review by oscarocastellanos — COMMENTED** [review]
@jinapurapu 
Icons does looks better and resolve confusion from users. I would remove the bar with the labels on top as I feel that part feels crowded now
image

**Review by djwfyi — COMMENTED** [review]
If we remove the legend, then we need tooltips on hover.
Or use labeled buttons instead of icons.

I think we need to explain the icons somewhere within the UI.

**Review by oscarocastellanos — APPROVED** [review]
LGTM

**Comment by kaankabalak** [comment]
Hi @jinapurapu, should we move the `ONLINE`/`OFFLINE` text under the icon as the table columns don't seem to align on smaller screen widths?

197640229-09f212a1-ce75-43fd-b8e5-bfd98f57bb0a

**Comment by kaankabalak** [comment]
> Could it be possible to just move them under certain screen or table sizes?

Yes, that should be possible @oscarocastellanos

**Comment by jinapurapu** [comment]
I've moved the text below the icons for all screen sizes. I'm planning to make another PR addressing the formatting of the table columns and headers, I can incorporate the side by side format for larger windows in that PR.

**Review by kaankabalak — APPROVED** [review]

**Review by dvaldivia — APPROVED** [review]

**Review by reivaj05 — APPROVED** [review]

**Review by prakashsvmx — APPROVED** [review]
The UI changes look good to me :+1: 
Hope we would move the online/offline check to the backend.

**Pull request merged**
