### PR TITLE
Upgrade to Go 1.16. Remove Go-Bind-assets in favor of embed.

### PR DESCRIPTION
**Pull request by dvaldivia**
Removes go-bindassets in favor of Go's `embed` package. This means the developer no longer needs to checking the large `go-bindassets.go` file but instead the delta from `portal-ui/build/` in order to get the new files embedded into the compiled go binary for console.

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Review by bexsoft — CHANGES_REQUESTED** [review]
I'm getting the following error trying to build the binary:

Screen Shot 2021-03-04 at 18 41 25

**Comment by harshavardhana** [comment]
> I'm getting the following error trying to build the binary:

`go mod tidy` should fix this.

**Review by bexsoft — APPROVED** [review]
LGTM, Test: OK

**Review by Alevsk — APPROVED** [review]
Tested, works fine

**Pull request merged**
