### PR TITLE
Fixed Tenant License crash in tenant details

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

Fixed a Tenant License page crash 

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

### CODE REVIEW

**Comment by allanrogerr** [comment]
@bexsoft How could I provoke this error?

**Review by jinapurapu — APPROVED** [review]

**Review by kaankabalak — APPROVED** [review]

**Comment by allanrogerr** [comment]
Also API tests are failing in this PR - why is this happening son consistently? @cniackz @pjuarezd Any ideas?

**Comment by bexsoft** [comment]
> @bexsoft How could I provoke this error?

In a previous version, go into any tenant details page of an unregistered cluster, then click on License option and you should see it

**Comment by allanrogerr** [comment]
> > @bexsoft How could I provoke this error?
> 
> In a previous version, go into any tenant details page of an unregistered cluster, then click on License option and you should see it

Tested and validated thanks!

**Review by allanrogerr — APPROVED** [review]

**Pull request merged**
