### PR TITLE
[WIP]  testcafe ui tests experiment with firefox in ci

### PR DESCRIPTION
**Pull request by prakashsvmx**
fix testcafe ui tests

### CODE REVIEW

**Comment by prakashsvmx** [comment]
@cesnietor  - in CI i tried with firefox. seems the tests are passing. 

so test failures in other PRs related to CI/testcafe/chrome specific. 

//cc @ramondeklein

**Comment by cesnietor** [comment]
>Suggestion: We can add tests with firefox as well in CI to isolate any issues in future.

I remember we started doing just chrome cause long time before it was also just working on chrome haha.
@prakashsvmx  is the issue in Chrome an actual issue? or just part of a bug in testcafe? like if you try to reproduce it?

**Comment by prakashsvmx** [comment]
@cesnietor  the issue is with testcafe and chrome version in CI

**Comment by prakashsvmx** [comment]
Closing as now the tests are passing in CI

**Pull request closed without merging**
