### PR TITLE
Use sync.Map for websocket cancelContext map

### PR DESCRIPTION
**Pull request by cesnietor**
There is a race condition while accessing the cancelContext map.
Since we delete and add values to it in goroutines we need to be sure there's no race condition.

This code is using a different pattern than that of trace or watch.

```
minio:goroutine 48288759572 [running]:
minio:runtime.fatal({0x2b2b988?, 0xc09d250001?})
minio:~runtime/panic.go:1096 +0x5c fp=0xc4791a7ad0 sp=0xc4791a7aa0 pc=0x43b8bc
minio:runtime.mapaccess1_fast64(0x26b9600, 0xc2c32bf740, 0x6)
minio:~runtime/map_fast64.go:22 +0x57 fp=0xc4791a7af0 sp=0xc4791a7ad0 pc=0x4148d7
minio:github.com/minio/console/restapi.(*wsMinioClient).objectManager.func2.1()
minio:~github.com/minio/console@v0.40.0/restapi/ws_objects.go:102 +0x273 fp=0xc4791a7fe0 sp=0xc4791a7af0 pc=0x16d9af3
```

### Test Steps:
- On Object browser
- List objects
- interact with them
- With a versioned bucket
- upload different versions for one
- rewind versions for objects

### CODE REVIEW

**Review by harshavardhana — CHANGES_REQUESTED** [review]
use sync.Map() @cesnietor

**Comment by cesnietor** [comment]
> use sync.Map() @cesnietor

@harshavardhana  what are the advantages of it? other than repetitive code?
I saw we would lose the type check.

**Comment by harshavardhana** [comment]
> > use sync.Map() @cesnietor
> 
> @harshavardhana what are the advantages of it? other than repetitive code? I need more feedback than just that haha. I saw we would lose the type check.

It avoids map and mutex. Just one data structure and simpler to use.

**Review by harshavardhana — APPROVED** [review]

**Comment by kannappanr** [comment]
@cesnietor PTAL build failure

**Comment by cesnietor** [comment]
> @cesnietor PTAL build failure

@kannappanr  build works, is just the vulnerability check, which can be addressed in other PR.

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
