### PR TITLE
Added Annotations, Labels and NodeSelector fields

### PR DESCRIPTION
**Pull request by Alevsk**
For Console/Encryption objects in the  CreateTenant Api

### CODE REVIEW

**Comment by dvaldivia** [comment]
you are not going to read the `image` from the `console` attribute? I see `consoleCOnfiguration` has the field in there

**Review by dvaldivia — DISMISSED** [review]

**Review by cesnietor — DISMISSED** [review]

**Review by cesnietor — COMMENTED** [review]
how is the console image property being used?

**Comment by Alevsk** [comment]
> how is the console image property being used?

will be used in the future, in the meantime we can use the existing `console_image` so we dont break the frontend

**Comment by Alevsk** [comment]
> you are not going to read the `image` from the `console` attribute? I see `consoleCOnfiguration` has the field in there

will be used in the future, in the meantime we can use the existing `console_image` so we dont break the frontend

**Review by cesnietor — APPROVED** [review]

**Review by dvaldivia — APPROVED** [review]

**Pull request merged**
