### PR TITLE
Move Register Component to Redux

### PR DESCRIPTION
**Pull request by dvaldivia**
Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

**Comment by prakashsvmx** [comment]
@dvaldivia could you please resolve the conflicts ?

**Comment by dvaldivia** [comment]
resolved @prakashsvmx

**Comment by prakashsvmx** [comment]
@dvaldivia 
The registration is done in SUBNET but the license is not reflected in Console.
Tried with the following flows: 
- Login
- API Key
- Registered via mc 
-



<details>

image

### When tried with local SUBNET dev
image


</details>

**Comment by dvaldivia** [comment]
@prakashsvmx can you also test on master? I think it's also broken there, I'll debug this and try to come up with a fix

**Comment by dvaldivia** [comment]
@prakashsvmx I've verified the same problem happens on master, will address it either in this PR or a separate one

**Comment by dvaldivia** [comment]
@prakashsvmx issue has been addressed

**Comment by allanrogerr** [comment]
Validated licence available in console
image

**Review by allanrogerr — APPROVED** [review]

**Review by prakashsvmx — APPROVED** [review]
One minor review comment.

#### Tested the following Flows: Changes look Good to me :+1: 
MinIO Console
- Online Registration
- API Key Registration
- Air-Gap Registration

Operator  Console
- API Key Registration

**Review by dilverse — APPROVED** [review]

**Pull request merged**
