### PR TITLE
Removed center alignment of forms in full screen

### PR DESCRIPTION
**Pull request by bexsoft**
fixes https://github.com/miniohq/engineering/issues/82

## What does this do?

Removed center alignment of fullscreen forms

## How does it look?

Screen Shot 2021-04-13 at 17 18 36
Screen Shot 2021-04-13 at 16 57 24
Screen Shot 2021-04-13 at 16 57 06
Screen Shot 2021-04-13 at 16 56 52
Screen Shot 2021-04-13 at 16 56 46
Screen Shot 2021-04-13 at 16 56 33
Screen Shot 2021-04-13 at 16 56 23

### CODE REVIEW

**Review by dvaldivia — APPROVED** [review]

**Review by Alevsk — APPROVED** [review]

**Comment by belvid** [comment]
This works great. One other thing, maybe disable (gray out) the save and next button until all required fields are filled.

**Comment by bexsoft** [comment]
> This works great. One other thing, maybe disable (gray out) the save and next button until all required fields are filled.

Sure, file a new ticket for it

**Comment by dvaldivia** [comment]
@belvid we will do that on a separate ticket

**Review by belvid — COMMENTED** [review]
This works great.

**Pull request merged**
