### PR TITLE
Fixes to Multiple IDP support in console

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

- Fixed Role ARN issue

- Fixed an issue with IDP redirect selection always pointing to first provider

- Refactored Multiple IDP support in UI for Console & Operator

- Fixed sorting issue in SSO dropdown

## How does it look?

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

### CODE REVIEW

**Review by reivaj05 — DISMISSED** [review]

**Review by dvaldivia — APPROVED** [review]

**Review by donatello — CHANGES_REQUESTED** [review]
I'm getting some error when I try to load the console:

image

This is on firefox, with console from this PR + minio master branch - not sure if I'm doing something wrong.

**Comment by bexsoft** [comment]
> I'm getting some error when I try to load the console:
> 
> image
> 
> This is on firefox, with console from this PR + minio master branch - not sure if I'm doing something wrong.

Please do `make assets` before doing `make` on MinIO master

**Review by donatello — CHANGES_REQUESTED** [review]
I got the build working fine now. Login works now, however, even when the role policy is set as consoleAdmin, I see only limited options in the account UI: 

image

It looks like permissions are not propagated properly?

**Review by donatello — APPROVED** [review]
With this fix in the server https://github.com/minio/minio/pull/15907 - this PR works as expected!

**Review by reivaj05 — APPROVED** [review]

**Pull request merged**
