### PR TITLE
Fix z-index of MainError component

### LINKED ISSUE #1255: MainError is being displayed behind Sidebar elements
It seems like on certain window sizes, the MainError component is behind the Sidebar elements (but not the background). It seems like the `z-index` value for both are set to 1000. We can increase the `z-index` for the MainError component to fix this.

Screen Shot 2021-11-24 at 5 31 53 PM

### PR DESCRIPTION
**Pull request by kaankabalak**
Fixes #1255

### CODE REVIEW

**Comment by kaankabalak** [comment]
All, I built the assets before sending in the PR, but do we build the assets only on releases now? I can make the necessary changes to the PR if required. Thanks in advance for the help!

**Comment by dvaldivia** [comment]
@kaankabalak yes, we only send assets in release PRs now

**Comment by kaankabalak** [comment]
Ok, updating the PR now 👍

**Review by dvaldivia — APPROVED** [review]

**Review by prakashsvmx — APPROVED** [review]
lgtm.

**Review by bexsoft — APPROVED** [review]

**Pull request merged**
