### PR TITLE
Move heal and watch to tenant details view on operator-ui

### PR DESCRIPTION
**Pull request by cesnietor**
fixes https://github.com/minio/console/issues/418

Changes were done on websocket implementations and on UI.
Screen Shot 2020-11-25 at 12 40 17 PM
Screen Shot 2020-11-25 at 12 40 28 PM

Should be testing deploying console as console operator on a kubernetes environment.

### CODE REVIEW

**Review by Alevsk — CHANGES_REQUESTED** [review]
Will test and make sure there's no TLS issues with websockets

**Comment by Alevsk** [comment]
On the watch screen when I select a bucket and then click start im seeing the TLS verification Error (MinIO is running with TLS enabled), ill quickly debug this and send a pr to your branch @cesnietor 

```
│ 2020/11/25 23:34:28 watch started                                                                                                                          │
│ 2020/11/25 23:34:28 error on watch: Get "https://minio.default.svc.cluster.local/songs/?location=": x509: certificate signed by unknown authority          │
│ 2020/11/25 23:34:28 watch stopped                                                                                                                          │
│ 2020/11/25 23:34:28 error on ReadMessage: read tcp 127.0.0.1:9443->127.0.0.1:47990: use of closed network connection
```

**Comment by Alevsk** [comment]
> On the watch screen when I select a bucket and then click start im seeing the TLS verification Error (MinIO is running with TLS enabled), ill quickly debug this and send a pr to your branch @cesnietor
> 
> ```
> │ 2020/11/25 23:34:28 watch started                                                                                                                          │
> │ 2020/11/25 23:34:28 error on watch: Get "https://minio.default.svc.cluster.local/songs/?location=": x509: certificate signed by unknown authority          │
> │ 2020/11/25 23:34:28 watch stopped                                                                                                                          │
> │ 2020/11/25 23:34:28 error on ReadMessage: read tcp 127.0.0.1:9443->127.0.0.1:47990: use of closed network connection
> ```

I sent a PR to fix the above issue @cesnietor https://github.com/cesnietor/console/pull/3, then I have a second PR https://github.com/cesnietor/console/pull/4 but this one requires a release on mc.

**Review by Alevsk — APPROVED** [review]
Tested LGTM

**Review by bexsoft — APPROVED** [review]

**Pull request merged**
