### PR TITLE
Omit detailedMessage from login errors

### PR DESCRIPTION
**Pull request by jinapurapu**
Avoids passing detailed error to frontend login errors, no longer differentiable between existing/non-existing Users. 

Existing user, wrong password:
Screenshot 2023-12-05 at 2 32 37 PM

User doesn't exist:

Screenshot 2023-12-05 at 2 32 22 PM

Part of https://github.com/miniohq/engineering/issues/1306

### CODE REVIEW

**Comment by prakashsvmx** [comment]
@jinapurapu , could you check the `gofumpt` as CI fails ?

**Comment by prakashsvmx** [comment]
@jinapurapu  there are some test failures , may be related to the messages

**Comment by bexsoft** [comment]
@jinapurapu Please change only the messages in Login APIs, the errors from Object browser are required as there is to handle a specific corner case

**Review by bexsoft — APPROVED** [review]
LGTM

**Review by cesnietor — APPROVED** [review]
Thanks for addressing the comments, LGTM

**Pull request merged**
