### PR TITLE
Made Improvements to Console System

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

- Removed Lato font references in code making Inter font as default
- Rejected direct requests to static assets folders

## How does it look?

Screenshot 2023-01-18 at 18 03 24
Screenshot 2023-01-18 at 18 03 09

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

### CODE REVIEW

**Comment by kaankabalak** [comment]
Just a quick piece of feedback, the fonts enclosed in red don't seem to be Inter. To make it easier to see the difference, I have highlighted the fonts that are actually Inter in blue rectangles:

213324731-ce849d08-4a69-46ad-86e0-7e3b8181d267

**Comment by bexsoft** [comment]
> Just a quick piece of feedback, the fonts enclosed in red don't seem to be Inter. To make it easier to see the difference, I have highlighted the fonts that are actually Inter in blue rectangles:
> 
> 213324731-ce849d08-4a69-46ad-86e0-7e3b8181d267

Thank you @kaankabalak!, Fixed.

Please note that we will be doing some other changes in mds to handle these boxes, this will include some adjustments to white-space wrap and some others.

Screenshot 2023-01-18 at 23 08 31

**Review by prakashsvmx — APPROVED** [review]
LGTM :+1:

**Comment by prakashsvmx** [comment]
@bexsoft  shall we also  disable source map  for production builds ? 
`GENERATE_SOURCEMAP=false`

**Comment by bexsoft** [comment]
> @bexsoft shall we also disable source map for production builds ? `GENERATE_SOURCEMAP=false`

Yes, we can disable it in a new PR

**Review by kaankabalak — APPROVED** [review]

**Pull request merged**
