### PR TITLE
Adding the restart API test

### PR DESCRIPTION
**Pull request by cniackz**
Fixes https://github.com/miniohq/engineering/issues/521

The idea here is to add a test for `restart` end point.

I noticed that `restart` is taking long time compared to other end points, even using `mc` command is time consuming.
So the trick is to increase the timeout in our client to wait until this is properly performed and we get 204 as response:

`Timeout: 2000 * time.Second, // increased timeout since restart takes time, more than other APIs.`

### CODE REVIEW

**Review by prakashsvmx — APPROVED** [review]
LGTM.

**Comment by prakashsvmx** [comment]
We could add `admin_api_integration_test.go` to differentiate `AdminAPI`  and `UserAPI`  tests as per swagger tags.
@cniackz

**Comment by cniackz** [comment]
Hello @cniackz I have new issue to address your comment:
https://github.com/miniohq/engineering/issues/541
I will create a new PR with this suggestion.
Thank you!

**Review by adfost — APPROVED** [review]

**Review by jinapurapu — APPROVED** [review]

**Review by bexsoft — APPROVED** [review]
LGTM

**Pull request merged**
