### PR TITLE
Added replication bulk modal to buckets list

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?
Implements replication modal for bulk edit

## How does it look?
Screen Shot 2021-03-31 at 22 42 06
Screen Shot 2021-03-31 at 22 41 59
Screen Shot 2021-03-31 at 22 41 52
Screen Shot 2021-03-31 at 22 41 45

### CODE REVIEW

**Review by dvaldivia — APPROVED** [review]

**Comment by Alevsk** [comment]
There's a weird bug in which every time I type a letter the input field lost focus
Screen Shot 2021-04-02 at 15 40 21

I could not pass this step, even if the buckets exist on the remote cluster im still getting the same error
Screen Shot 2021-04-02 at 15 41 47

**Review by Alevsk — CHANGES_REQUESTED** [review]
There's a weird bug in which every time I type a letter the input field lost focus
Screen Shot 2021-04-02 at 15 40 21

I could not pass this step, even if the buckets exist on the remote cluster im still getting the same error
Screen Shot 2021-04-02 at 15 41 47

**Comment by Alevsk** [comment]
Also root credentials dont seem to work for bucket replication, maybe we should put a message indicating that to the user

**Comment by dvaldivia** [comment]
@Alevsk I think we forbid using root credentials for a lot of things, even STS, perhaps we should add that in the readme of console as well

**Comment by dvaldivia** [comment]
only two things:

Still see the double scrollbar:

Screen Shot 2021-04-05 at 8 58 32 AM

and I don't see any loading indicating that blocks the UI while I wait on this other step:

Screen Shot 2021-04-05 at 9 07 27 AM

**Review by Alevsk — DISMISSED** [review]

**Review by dvaldivia — APPROVED** [review]

**Review by Alevsk — APPROVED** [review]

**Pull request merged**
