### PR TITLE
separate operator binary code to reduce binary size

### PR DESCRIPTION
**Pull request by harshavardhana**
remove logsearchapi dependency, no definitive struct
marshalling is needed since UI is schemaless for
search response.

### CODE REVIEW

**Comment by bexsoft** [comment]
Is there any special configuration to run console server & operator server? If I try to run from source code I get `exit status 1` message, this happens also running from build executable (no error is seen, but application closes)

**Comment by harshavardhana** [comment]
> Is there any special configuration to run console server & operator server? If I try to run from source code I get `exit status 1` message, this happens also running from build executable (no error is seen, but application closes)

Operator code won't work if not running in k8s cluster @bexsoft you can't test that locally. This build change is to allow other dependent projects to selectively ignore `operator` code. 

So if you do `make install` it always builds with operator to keep backward compatibility.

**Comment by dvaldivia** [comment]
can you rebase @harshavardhana ?

**Comment by harshavardhana** [comment]
> can you rebase @harshavardhana ?

done @dvaldivia

**Comment by dvaldivia** [comment]
I guess we need an additional `make` target for the operator binary, include both binaries in the container and update the kubernetes resources to use the `./operator operator` binary instead of `./console operator` @harshavardhana , wanna do that in this PR?

**Comment by harshavardhana** [comment]
> I guess we need an additional `make` target for the operator binary, include both binaries in the container and update the kubernetes resources to use the `./operator operator` binary instead of `./console operator` @harshavardhana , wanna do that in this PR?

It's not needed that is not the intention here. It is mainly meant to pave way for builds to be generated without operator code, i.e MinIO.

Binary is going be still the same for this repo, nothing changes.

**Comment by dvaldivia** [comment]
one more rebase please @harshavardhana 🙏

**Review by dvaldivia — APPROVED** [review]

**Comment by harshavardhana** [comment]
@bexsoft @Alevsk PTAL

**Review by cniackz — APPROVED** [review]

**Pull request merged**
