### PR TITLE
React 18 initial migration

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

Adds initial migration for React 18.

In order to test this, please delete your node_modules folder & do `yarn install`

### Notes
- There is an incompatibility on react 18 and react-virtualized. This happens because the new rendering method on React doesn't update the DOM unless is really necessary. In an upcoming PR a replacement for this library will be done (Please omit resizing issues with table wrapper & virtual lists)
- React router will be updated in an upcoming PR. This will help a lot with re-renders during page changes

- Please inform any style issues that you may detect as mui was updated too with this change

### CODE REVIEW

**Comment by prakashsvmx** [comment]
Create a bucket -> prefix -> upload a file -> select file -> delete -> click back arrow in the path text box
(also the deleted file path is retained in the path text box. some times with prefix and sometimes without prefix)

<summary> Observed a crash  </summary>

<details>

image

Delete button (red) color is missing

image
image


</details>

**Comment by jinapurapu** [comment]
Browse button overhangs box if window narrowed
Screenshot from 2022-05-27 12-07-25

**Comment by cniackz** [comment]
Re ran `Workflow / Permissions Tests Part 4`

**Comment by cniackz** [comment]
Intermittent problem, all tests are passing now:

Screen Shot 2022-05-27 at 5 22 10 PM

**Review by cniackz — APPROVED** [review]
LGTM

**Review by dvaldivia — DISMISSED** [review]

**Comment by bexsoft** [comment]
> 

The crash issue is not related to this PR. Will fix it in a new one. All secondary buttons should be fixed by now:

Screen Shot 2022-05-27 at 18 17 35
Screen Shot 2022-05-27 at 18 17 27

**Comment by bexsoft** [comment]
> Browse button overhangs box if window narrowed Screenshot from 2022-05-27 12-07-25

Solved:
Screen Shot 2022-05-27 at 18 17 15

**Review by dvaldivia — APPROVED** [review]

**Review by cniackz — APPROVED** [review]
LGTM

**Review by jinapurapu — APPROVED** [review]

**Pull request merged**
