### PR TITLE
Move Create Tenant to Thunk

### PR DESCRIPTION
**Pull request by dvaldivia**
Move the Create Tenant call into a thunk to reduce the number of re-renders on the tenant add screen.

ECB0E9B6-3A6A-42CF-B48F-F523187C88A3-36099-0001CECC1DAC250A

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

**Comment by cniackz** [comment]
Ok, started testing with this ON:
`Highlight updates when components render.`
image

**Comment by cniackz** [comment]
Amazing few renders:

https://user-images.githubusercontent.com/6667358/170587685-8b2abf6a-56e7-47e5-88a9-31a9b66b8b2f.mov

**Review by cniackz — APPROVED** [review]
LGTM

**Review by jinapurapu — APPROVED** [review]

**Review by bexsoft — APPROVED** [review]
LGTM

**Pull request merged**
