### PR TITLE
update all go-deps

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by harshavardhana** [comment]
Let's make a console release tomorrow before March 12th.

**Comment by harshavardhana** [comment]
This is needed for MinIO update.

**Review by dvaldivia — APPROVED** [review]

**Review by dvaldivia — APPROVED** [review]

**Review by bexsoft — APPROVED** [review]

**Comment by harshavardhana** [comment]
Permission tests have been failing not sure what it is.

**Comment by bexsoft** [comment]
> Permission tests have been failing not sure what it is.

Seems like a real failure, did something changed on MinIO side for the policies?

**Pull request merged**
