### PR TITLE
chore: disable animation for login page

### PR DESCRIPTION
**Pull request by cgpoh**
Following @dvaldivia to disable animation for login page until [kubernetes/kubectl#1368](https://github.com/kubernetes/kubectl/issues/1368) get resolved

### CODE REVIEW

**Comment by dvaldivia** [comment]
I don't think we should disable the animation on the console itself, since it's expected to expose the console via ingress or similar, for the operator UI perhaps not everyone will want to expose it so I deem it necessary to disable the animation, perhaps for Console if we really need this we should disable it via environment variable

**Comment by cgpoh** [comment]
Thanks for the comment. We can’t use ingress due to security reason and we can only use port forward to login to minio console. I will try to use environment variable to allow turning on/off the animation.

**Comment by dnskr** [comment]
Could someone review this please?

**Comment by bexsoft** [comment]
Hi @cgpoh!, Thank you for your contribution

For this behavior to work, we will need some changes in MinIO as we don't support the ability to modify JS files directly into the server. We have created this PR that will help to achieve this behavior: https://github.com/minio/console/pull/2799 using env variables directly that can be read & managed directly from MinIO

We will be implementing the required change in MinIO as well. We will be closing this PR, Please feel free to reopen in case  you think something is missing

**Comment by cgpoh** [comment]
> Hi @cgpoh!, Thank you for your contribution
> 
> For this behavior to work, we will need some changes in MinIO as we don't support the ability to modify JS files directly into the server. We have created this PR that will help to achieve this behavior: #2799 using env variables directly that can be read & managed directly from MinIO
> 
> We will be implementing the required change in MinIO as well. We will be closing this PR, Please feel free to reopen in case you think something is missing

Hi @bexsoft , thanks for your help!

**Pull request closed without merging**
