### PR TITLE
Invalidate console session when minio user doesn't exists

### PR DESCRIPTION
**Pull request by Alevsk**
## Testing

- Create new user and assign policy:

```
./mc admin user add orcadmin alevsk alevsk12356
./mc admin policy set orcadmin mcsAdmin user=alevsk
```
- Login to console and list buckets/users/policies etc
- Delete the user using `mc`
```
./mc admin user remove orcadmin alevsk
```
- Try to navigate some more in Console, you should be redirected to the login screen since your session will be invalidated

Fixes https://github.com/minio/console/issues/306

### CODE REVIEW

**Comment by dvaldivia** [comment]
Will this log out the user on the UI?

**Review by dvaldivia — APPROVED** [review]

**Review by cesnietor — CHANGES_REQUESTED** [review]
testing.

**Review by cesnietor — DISMISSED** [review]
Tested, just if the user is disabled it won't redirect to login page but as discussed previously  this will be investigated.
LGTM.

**Comment by Alevsk** [comment]
> Will this log out the user on the UI?

yes, in the UI user will be redirected to the login screen, we already have some logic to do that

**Review by dvaldivia — APPROVED** [review]

**Review by cesnietor — APPROVED** [review]

**Pull request merged**
