### PR TITLE
Add upload api and integrate it with object browser on UI

### PR DESCRIPTION
**Pull request by cesnietor**
Upload api can be done doing POST on `/buckets/{bucket_name}/objects/upload?prefix=folder/file1.doc`
Api only supports single file upload.
Using `multipart/form-data` content-type.

Screen Shot 2020-10-14 at 5 47 36 PM
Screen Shot 2020-10-14 at 5 48 27 PM

### CODE REVIEW

**Comment by dvaldivia** [comment]
All the files I upload end up being 0KB in size

Screen Shot 2020-10-14 at 6 25 30 PM

**Comment by cesnietor** [comment]
you need to wait to the crawler, after some minutes minio returns the size.

**Comment by cesnietor** [comment]
@dvaldivia  as long as you can upload and download the same file it should be fine.

**Comment by cesnietor** [comment]
fixed @dvaldivia

**Review by bexsoft — APPROVED** [review]
LGTM, Test OK. Are we going to show an alert for files bigger than 128MB?, I was able to select a 6.78GB file

**Comment by cesnietor** [comment]
> LGTM, Test OK. Are we going to show an alert for files bigger than 128MB?, I was able to select a 6.78GB file
the limit will no longer exist :)

**Review by dvaldivia — APPROVED** [review]

**Pull request merged**
