### PR TITLE
Fix Console Warnings on Browser

### PR DESCRIPTION
**Pull request by dvaldivia**
Fixes all the browser warnings cause by passing the classes prop to child components

### before
IMG_4039

### After

Screen Shot 2021-12-07 at 4 00 18 PM
Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

**Review by bexsoft — COMMENTED** [review]
LGTM

**Review by bexsoft — DISMISSED** [review]

**Comment by prakashsvmx** [comment]
The search box sizes have changed (UX).

image

Extra border:
image

**Comment by dvaldivia** [comment]
@prakashsvmx aah, this was my concern with fixing this, if we need to push down styles we should either create shared classes or leverage the `sx` component, will look into these 3 things you found

**Review by bexsoft — APPROVED** [review]
LGTM

**Review by Alevsk — APPROVED** [review]

**Pull request merged**
