### PR TITLE
Add progress bar on UI

### PR DESCRIPTION
**Pull request by cesnietor**
fixes: https://github.com/minio/console/issues/415
Loading component [edited]:
Screen Shot 2020-12-17 at 7 44 11 PM

Also show notification component, shared across the application:
Screen Shot 2020-12-17 at 5 05 32 PM

### CODE REVIEW

**Review by dvaldivia — APPROVED** [review]

**Comment by belvid** [comment]
@cesnietor  Can you make the loading line 1 pixel thicker? and also, can the unloaded part of the line be this color? ##d9deea

Thanks!

**Comment by cesnietor** [comment]
> @cesnietor Can you make the loading line 1 pixel thicker? and also, can the unloaded part of the line be this color? #d9deea
> 
> Thanks!

done @belvid

**Review by belvid — DISMISSED** [review]
Great, thank you!

**Review by bexsoft — CHANGES_REQUESTED** [review]
Seems to be working only for the first time, if I upload multiple files (one after another) the message it's only shown for the first file

https://user-images.githubusercontent.com/33497058/102570956-14a86700-40ae-11eb-9af3-478c5540d910.mp4

**Comment by dvaldivia** [comment]
for me for large files it only fills until half

**Comment by cesnietor** [comment]
> Seems to be working only for the first time, if I upload multiple files (one after another) the message it's only shown for the first file
> 
> Screen.Recording.2020-12-17.at.21.19.27-hevcmp4.mp4

fixed @bexsoft

**Comment by cesnietor** [comment]
> for me for large files it only fills until half

@dvaldivia  this might be the api, since it times out, I added a way to catch and display the error on the UI. This PR only changes UI. We might need to check the API to keep the connection alive.

**Review by bexsoft — APPROVED** [review]
LGTM, Test OK

**Review by dvaldivia — APPROVED** [review]

**Pull request merged**
