### PR TITLE
Fix 1299: Tools menu not showing for Heal Only Policy

### LINKED ISSUE #1299: For setups that are not distributed, Heal page renders empty
For setups that are not distributed, the heal page renders empty due to the following code on portal-ui/src/screens/Console/Heal/Heal.tsx:255-257:

```
  if (!distributedSetup) {
    return null;
  }
```

Screen Shot 2021-12-07 at 2 10 40 AM

We might want to redirect the user if this feature isn't available on non-distributed setups. Alternatively, we can either render a page communicating that this feature is not available for non-distributed setups or not display/disable this option on the sidebar/Tools page links.

### PR DESCRIPTION
**Pull request by dvaldivia**
Fixes #1299 

Screen Shot 2021-12-07 at 11 11 46 AM

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

**Review by kaankabalak — CHANGES_REQUESTED** [review]
When I log in as a user with only Heal policies, for the first time I display the page, the enabled options on the Tools pages look fine. However, when I log out, log in as a separate user with different permissions and navigate to the Tools page, the enabled options that I see are the ones that were enabled for the previous user. The options are only updated when I refresh the page. Please refer to the video below for further details.


https://user-images.githubusercontent.com/27314853/145094938-bf57b428-15a7-4b5e-a000-aaacc44e3313.mov



The policy for the `heal` user is listed below:

```
{
	"Version": "2012-10-17",
	"Statement": [{
			"Action": [
        "admin:Heal"
			],
			"Effect": "Allow",
			"Sid": ""
		}
	]
}
```

Whereas, the policy for the `diagnostics` user is given below:

```
{
	"Version": "2012-10-17",
	"Statement": [{
			"Action": [
        "admin:OBDInfo"
			],
			"Effect": "Allow",
			"Sid": ""
		}
	]
}
```

**Comment by dvaldivia** [comment]
that's interesting, it's a problem only with logout+loging situations, if you refresh the page, the problem goes away, I'm investigating

**Comment by dvaldivia** [comment]
@kaankabalak fixed! it was caused by a `const` on utils, moved that to the component

**Review by kaankabalak — APPROVED** [review]

**Review by jinapurapu — APPROVED** [review]

**Comment by bexsoft** [comment]
There is an issue with `endpoints.go` where we are not returning all the available endpoints for permissions, for example:


Screen Shot 2021-12-07 at 15 32 21

This is not related to this change. this PR is ok

**Review by bexsoft — APPROVED** [review]
LGTM

**Comment by harshavardhana** [comment]
Is it intentional to have `heal` without `Heal` - 'h' is not capitalized whereas for `Watch` - 'W' is capitalized. 

I feel this is inconsistent in the Tools menu. @dvaldivia @bexsoft

**Comment by dvaldivia** [comment]
@harshavardhana nice catch, will fix

**Pull request merged**
