### PR TITLE
Move New Credentials to separate component for Add Tenant

### PR DESCRIPTION
**Pull request by dvaldivia**
Moves the New Credentials component to an intermediate component to avoid `AddTenant` component re-rendering when a new tenant has been added.

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

**Comment by cniackz** [comment]
Tested locally, I do observe much less renders with this on the New Tenant Credentials:
https://drive.google.com/file/d/1cksy3UrzHnOc-GxXdzoUraV8-JcJ61eE/view?usp=sharing

**Comment by cniackz** [comment]
https://github.com/minio/console/runs/6679742181?check_suite_focus=true

```
Result:
50.6%
It is smaller than threshold (50.7%) value, failed!
Error: Process completed with exit code 1.
```

**Review by cniackz — APPROVED** [review]
It looks good to me

**Review by cniackz — COMMENTED** [review]
As incredible as it seems this PR is decreasing our coverage but not other PRs like:
https://github.com/minio/console/pull/2058
where no new lines are added just one line is modified.
The question is, should we decrease the coverge threshold because of this? or should we add a test to increase it here? Up to you guys, it is only by .1 per cent the difference. But ideally I would like to have all tests passing to approve it.

**Comment by dvaldivia** [comment]
@cniackz let's increase the coverage on a separate PR

**Review by bexsoft — APPROVED** [review]
LGTM

**Pull request merged**
