### PR TITLE
remove quota FIFO support

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by dvaldivia** [comment]
@harshavardhana is this also gone from the server?

**Comment by harshavardhana** [comment]
> @harshavardhana is this also gone from the server?

Yes it will be gone but need this PR first.

**Review by prakashsvmx — APPROVED** [review]
Tested:

- On Update of Existing Bucket with  FIFO Quota 
- On new Bucket creation
- Update of Bucket Quota post creation

Changes look good to me. :+1: 

Few UX Suggestions which can be addressed later:
- `Quota_type in body should be one of [hard]` error message can be updated  When editing an existing FIFO Quota and saving without selecting the Type. ( or we can default to hard always )
- `Quota Type` selection can be removed as it would be the default , and Quota label can be " Quota Size"

**Review by bexsoft — APPROVED** [review]
LGTM

**Pull request merged**
