### PR TITLE
Create bug_report.md

### PR DESCRIPTION
**Pull request by allanrogerr**

### CODE REVIEW

**Review by bexsoft — APPROVED** [review]
LGTM

**Review by cesnietor — APPROVED** [review]

**Review by bexsoft — CHANGES_REQUESTED** [review]
reviewing location

**Comment by cesnietor** [comment]
Seems test `Delete button is enabled for object that matches prefix inside bucket` is failing but it's unrelated to this PR.

**Comment by cesnietor** [comment]
ahh true @allanrogerr  location should be `.github/ISSUE_TEMPLATE`

**Comment by allanrogerr** [comment]
> reviewing location

I tested on my repo to be sure:

1. See https://github.com/allanrogerr/minio/blob/master/.github/ISSUE_TEMPLATE/bug_report.md. Observe string `NOTE 2`
2. Now try to raise an issue
3. https://github.com/allanrogerr/minio/issues/new?assignees=&labels=community%2C+triage&projects=&template=bug_report.md&title=
4. Observe the same string `NOTE 2`

**Comment by cesnietor** [comment]
@allanrogerr  but the file needs to be in `.github/ISSUE_TEMPLATE` and the PR is having it in `.github/workflows/ISSUE_TEMPLATE/`

See docs https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository

**Comment by allanrogerr** [comment]
@cesnietor @bexsoft PTAL

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
Also add `config.yml` file and also feature_request template as well.

**Review by bexsoft — APPROVED** [review]

**Pull request merged**
