### PR TITLE
Added CPU size selector & add tenant cleanup

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

Adds CPU selection to create tenant screen, also fixed validations for number of servers, drivers per server & CPU selection to avoid entering ., - and other non-valid numeric signs

## How does it look?
Screen Shot 2021-12-16 at 0 56 34
Screen Shot 2021-12-16 at 0 56 16

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

### CODE REVIEW

**Review by prakashsvmx — COMMENTED** [review]
An Observation:
-------------
The CPU selection resets to initial value if navigated to some other tab in tenant creation form.

[cpu-selection-reset.zip](https://github.com/minio/console/files/7726872/cpu-selection-reset.zip)


Otherwise the the tenant is created with the specified resource (limit cpu, memory)
Verified with Yaml and describing the pod. :+1:

**Review by dvaldivia — DISMISSED** [review]

**Comment by jinapurapu** [comment]
Invalid CPU Configuration error does not show when leading zero left off of decimal entry
Screenshot from 2021-12-16 13-15-47

**Comment by bexsoft** [comment]
> Invalid CPU Configuration error does not show when leading zero left off of decimal entry Screenshot from 2021-12-16 13-15-47

Fixed:
Screen Shot 2021-12-16 at 15 36 41

**Comment by bexsoft** [comment]
> ## An Observation:
> The CPU selection resets to initial value if navigated to some other tab in tenant creation form.
> 
> [cpu-selection-reset.zip](https://github.com/minio/console/files/7726872/cpu-selection-reset.zip)
> 
> Otherwise the the tenant is created with the specified resource (limit cpu, memory) Verified with Yaml and describing the pod. 👍

Fixed

**Review by dvaldivia — APPROVED** [review]

**Review by prakashsvmx — APPROVED** [review]
LGTM.

**Review by dvaldivia — APPROVED** [review]

**Pull request merged**
