### PR TITLE
Added URL support to object view

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

- Added URL support to object view
- Refactored & simplified requests

## How does it look?

Screen Shot 2022-04-11 at 21 53 49

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

### CODE REVIEW

**Review by dvaldivia — DISMISSED** [review]
Tested. LGTM.

**Comment by prakashsvmx** [comment]
@bexsoft 

Flow 1: Create a bucket -> upload Object -> Refresh -> Create new path (Observe the Crash)
i got the below error. Refreshing the browser also  does not help.


Video:

<details>

https://user-images.githubusercontent.com/23444145/163178537-1ad3e46f-bde0-48de-8bfb-883f8d6e3279.mp4

</details>

<details>
```


Uncaught TypeError: Cannot read properties of null (reading 'length')
    at ObjectDetailPanel.tsx:204:1
    at invokePassiveEffectCreate (react-dom.development.js:23488:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3946:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3995:1)
    at invokeGuardedCallback (react-dom.development.js:4057:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23575:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11277:1)
    at flushPassiveEffects (react-dom.development.js:23448:1)
    at performSyncWorkOnRoot (react-dom.development.js:22270:1)
(anonymous) @ ObjectDetailPanel.tsx:204
invokePassiveEffectCreate @ react-dom.development.js:23488
callCallback @ react-dom.development.js:3946
invokeGuardedCallbackDev @ react-dom.development.js:3995
invokeGuardedCallback @ react-dom.development.js:4057
flushPassiveEffectsImpl @ react-dom.development.js:23575
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11277
flushPassiveEffects @ react-dom.development.js:23448
performSyncWorkOnRoot @ react-dom.development.js:22270
(anonymous) @ react-dom.development.js:11328
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11277
flushSyncCallbackQueueImpl @ react-dom.development.js:11323
flushSyncCallbackQueue @ react-dom.development.js:11310
scheduleUpdateOnFiber @ react-dom.development.js:21894
dispatchAction @ react-dom.development.js:16140
(anonymous) @ ObjectDetailPanel.tsx:232
Promise.then (async)
(anonymous) @ ObjectDetailPanel.tsx:221
invokePassiveEffectCreate @ react-dom.development.js:23488
callCallback @ react-dom.development.js:3946
invokeGuardedCallbackDev @ react-dom.development.js:3995
invokeGuardedCallback @ react-dom.development.js:4057
flushPassiveEffectsImpl @ react-dom.development.js:23575
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11277
flushPassiveEffects @ react-dom.development.js:23448
performSyncWorkOnRoot @ react-dom.development.js:22270
(anonymous) @ react-dom.development.js:11328
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11277
flushSyncCallbackQueueImpl @ react-dom.development.js:11323
flushSyncCallbackQueue @ react-dom.development.js:11310
discreteUpdates$1 @ react-dom.development.js:22421
discreteUpdates @ react-dom.development.js:3757
dispatchDiscreteEvent @ react-dom.development.js:5890



```


<details>

**Comment by bexsoft** [comment]
> @bexsoft
> 
> Flow 1: Create a bucket -> upload Object -> Refresh -> Create new path (Observe the Crash) i got the below error. Refreshing the browser also does not help.
> 
> Video:

Issue Fixed

**Review by dvaldivia — APPROVED** [review]

**Review by prakashsvmx — APPROVED** [review]
Tested
- Navigating a console address bar url from another browser where the user is logged in.
-  Create new path -> Upload -> Refresh 
-  No session -> Path URL -> Navigates to bucket list (default)
- With logged in session -> It navigates to the desired path/prefix

Changes look good to me :+1:

**Comment by prakashsvmx** [comment]
@bexsoft  There are `console.log` hope they are added for debugging if any issues.  may be we can remove later ?

**Comment by bexsoft** [comment]
> @bexsoft There are `console.log` hope they are added for debugging if any issues. may be we can remove later ?
> 
> `console.log("SET PATH");` `console.log("STE");` `console.log("1");` `console.log("2");`

Yes, my fault :/, let me do another PR to remove this. Thank you! =D

**Pull request merged**
