### PR TITLE
Create Tenant Namespace Field move to Thunks

### PR DESCRIPTION
**Pull request by dvaldivia**
Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

**Comment by cniackz** [comment]
Tested locally for the renders:

[lot-less-renders.mov.zip](https://github.com/minio/console/files/8799836/lot-less-renders.mov.zip)

**Comment by cniackz** [comment]
Functionality is not affected, tenant can be created:

Screen Shot 2022-05-30 at 12 51 53 PM

**Review by cniackz — APPROVED** [review]
It looks good to me:

- Less renders
- Functionality is same, not affected
- All tests are passing

**Review by bexsoft — APPROVED** [review]
LGTM

**Pull request merged**
