### PR TITLE
Tweak some headers with the new names

### PR DESCRIPTION
**Pull request by dvaldivia**
Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

**Review by Alevsk — DISMISSED** [review]

**Review by bexsoft — APPROVED** [review]
LGTM

**Review by bexsoft — CHANGES_REQUESTED** [review]
Please fix warnings:
```
src/screens/Console/HealthInfo/HealthInfo.tsx
  Line 48:8:   'BackLink' is defined but never used   @typescript-eslint/no-unused-vars
  Line 51:10:  'IAM_PAGES' is defined but never used  @typescript-eslint/no-unused-vars

src/screens/Console/Speedtest/Speedtest.tsx
  Line 40:3:  'IAM_PAGES' is defined but never used  @typescript-eslint/no-unused-vars
  Line 45:8:  'BackLink' is defined but never used   @typescript-eslint/no-unused-vars

```

**Comment by dvaldivia** [comment]
@bexsoft no need to tell me, the tests would have failed :-)

**Review by bexsoft — APPROVED** [review]
LGTM

**Review by kaankabalak — APPROVED** [review]

**Pull request merged**
