### PR TITLE
Add Server Metrics Info Tab

### PR DESCRIPTION
**Pull request by dvaldivia**
Screen Shot 2022-09-27 at 6 01 06 PM
Screen Shot 2022-09-27 at 6 00 50 PM

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

**Review by bexsoft — APPROVED** [review]
LGTM

**Review by bexsoft — APPROVED** [review]
LGTM

**Comment by prakashsvmx** [comment]
@dvaldivia @bexsoft  while testing  found that there was a crash and incorrect border . so sent a commit to fix them. PTAL.
Thank you in advance.

**Comment by jinapurapu** [comment]
Should there be a Browse button on the Buckets card of the Prometheus Dashboard?

**Comment by bexsoft** [comment]
> Should there be a Browse button on the Buckets card of the Prometheus Dashboard?

Yes, for consistency, I think this can be handled in a different PR

**Comment by bexsoft** [comment]
Please squash all the commits

**Comment by jinapurapu** [comment]
When you go to the Metrics screen with a bad Prometheus URL configured, it may not be obvious that the Info tab will be working when others are not. Maybe after some time of failure to get Prometheus data, an error message could indicate that there has been a problem, and that basic info is available under Info, or it could redirect to the Info tab?

**Comment by dvaldivia** [comment]
Fixed @jinapurapu 
Screen Shot 2022-10-07 at 1 34 55 PM

**Review by bexsoft — APPROVED** [review]
LGTM

**Review by reivaj05 — APPROVED** [review]

**Review by jinapurapu — APPROVED** [review]

**Pull request merged**
