### PR TITLE
Added Rename modal for filenames longer than 200 characters in Windows

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

Added Rename modal for filenames longer than 200 characters in Windows

## How does it look?

Captura3
Captura
Captura2

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

### CODE REVIEW

**Comment by cniackz** [comment]
Hello @bexsoft 

How do you test this change?. I put a file name of 201 characters, but I can download without any message on screen.
I am guessing this has to be tested on Windows only to see that modal, right?...

**Review by cniackz — APPROVED** [review]
LGTM

**Comment by bexsoft** [comment]
> Hello @bexsoft
> 
> How do you test this change?. I put a file name of 201 characters, but I can download without any message on screen. I am guessing this has to be tested on Windows only to see that modal, right?...

That's correct. Modal should only be visible on windows.

**Comment by prakashsvmx** [comment]
@bexsoft  a minor observation

I have used browserstack for testing

When  checkbox selection is used and clicking download does not prompt rename modal.
but when a row is clicked and download is pressed, then the rename modal is shown

https://user-images.githubusercontent.com/23444145/174941386-d1f43eec-9fc6-459f-95d0-b44281df3104.mp4


Also in the rename dialog, we could add more than 250 characters
image

**Comment by bexsoft** [comment]
> @bexsoft a minor observation
> 
> I have used browserstack for testing
> 
> When checkbox selection is used and clicking download does not prompt rename modal. but when a row is clicked and download is pressed, then the rename modal is shown
> 
>  rename_modal.mp4 
> Also in the rename dialog, we could add more than 250 characters image

Yes @prakashsvmx, In this case we want to enforce the zip download when checkbox is used to start the download, Let me check the length of the input issue

**Review by reivaj05 — APPROVED** [review]

**Pull request merged**
