### PR TITLE
fix: properly support FS/Gateway mode

### PR DESCRIPTION
**Pull request by harshavardhana**
fixes https://github.com/minio/console/issues/723

### CODE REVIEW

**Review by Alevsk — APPROVED** [review]

**Comment by harshavardhana** [comment]
More changes this PR needs is UI Elements need to be turned off if certain backend is chosen.

I am not aware of how to do that @dvaldivia @bexsoft

**Comment by bexsoft** [comment]
> More changes this PR needs is UI Elements need to be turned off if certain backend is chosen.
> 
> I am not aware of how to do that @dvaldivia @bexsoft

I will start working on that today @harshavardhana, in this case we will just need to return a flag during login and send it in the response so we can enable or disable items like we do with IAM

**Review by bexsoft — DISMISSED** [review]

**Comment by harshavardhana** [comment]
PTAL @Alevsk @dvaldivia

**Review by dvaldivia — APPROVED** [review]

**Comment by dvaldivia** [comment]
Tested. LGTM

**Review by bexsoft — APPROVED** [review]

**Pull request merged**
