### PR TITLE
Release v0.34.0

### PR DESCRIPTION
**Pull request by bexsoft**
## Test Results

Screenshot 2023-07-27 at 21 59 45
Screenshot 2023-07-27 at 21 59 35
Screenshot 2023-07-27 at 21 59 24

### CODE REVIEW

**Review by dvaldivia — DISMISSED** [review]

**Comment by harshavardhana** [comment]
We should take #2966

**Review by dvaldivia — APPROVED** [review]

**Review by kaankabalak — DISMISSED** [review]

**Review by jinapurapu — APPROVED** [review]

**Comment by harshavardhana** [comment]
is this ready to merge? I see CI failures

**Comment by bexsoft** [comment]
> is this ready to merge? I see CI failures

Not sure the reason of these failures, I've been testing in my local env with the latest MinIO server and no issues are seen locally
Screenshot 2023-07-28 at 13 39 29

**Comment by bexsoft** [comment]
Issue is only visible in chrome headless mode. doing extra research on this

**Pull request merged**
