### PR TITLE
Connected Share object modal

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

Connects Share object modal with API

## How does it look?

Screen Shot 2020-11-23 at 23 32 30
Screen Shot 2020-11-23 at 23 32 16
Screen Shot 2020-11-23 at 23 31 45
Screen Shot 2020-11-23 at 23 31 35
Screen Shot 2020-11-23 at 23 31 17

### CODE REVIEW

**Comment by kaankabalak** [comment]
> Screen Shot 2020-11-23 at 23 32 30
> 

Regardless of link length, should we make the field for the URL a single line as in the mockups given [here](https://xd.adobe.com/view/95ea2e03-344a-40f9-95c2-21bd98caaa1a-c0b9/screen/1d653483-5972-45fc-87e7-42badecaea51/)? We might want to consult @belvid or @Jayshreemagdum if we would like to make the field scrollable

**Review by cesnietor — CHANGES_REQUESTED** [review]
```
Creating an optimized production build...
Failed to compile.

./src/screens/Console/Common/FormComponents/DateSelector/DateSelector.tsx
  Line 209:34:  Unexpected use of 'name'  no-restricted-globals
  Line 232:60:  Unexpected use of 'name'  no-restricted-globals
  Line 254:55:  Unexpected use of 'name'  no-restricted-globals

Search for the keywords to learn more about each error.

```

**Comment by bexsoft** [comment]
> ```
> Creating an optimized production build...
> Failed to compile.
> 
> ./src/screens/Console/Common/FormComponents/DateSelector/DateSelector.tsx
>   Line 209:34:  Unexpected use of 'name'  no-restricted-globals
>   Line 232:60:  Unexpected use of 'name'  no-restricted-globals
>   Line 254:55:  Unexpected use of 'name'  no-restricted-globals
> 
> Search for the keywords to learn more about each error.
> ```

Fixed, it was an issue with lint rules that was not detected during development.

**Comment by bexsoft** [comment]
> > Screen Shot 2020-11-23 at 23 32 30
> 
> Regardless of link length, should we make the field for the URL a single line as in the mockups given [here](https://xd.adobe.com/view/95ea2e03-344a-40f9-95c2-21bd98caaa1a-c0b9/screen/1d653483-5972-45fc-87e7-42badecaea51/)? We might want to consult @belvid or @Jayshreemagdum if we would like to make the field scrollable

Will make it horizontal, in this case I will fill a new ticket to make this class a new component as there may be some issues with paddings:

Screen Shot 2020-11-24 at 13 07 26

**Review by kaankabalak — APPROVED** [review]

**Review by cesnietor — APPROVED** [review]

**Pull request merged**
