### PR TITLE
Added Exclude Folders & Exclude Prefixes support

### LINKED ISSUE #2417: [Feature request] Web Console add new setting about version exclude-prefixes
Since we could use mc command to set specific prefix with no version ability: mc version enable --excluded-prefixes
And using mc version info --json to display configured exclude prefix.

It would be so nice if web console can support mc version enable excluded-prefixes configuration.

### PR DESCRIPTION
**Pull request by bexsoft**
fixes #2417

## What does this do?

Added Exclude Folders & Exclude Prefixes support to Create Bucket & Bucket details pages

## How does it look?

Screenshot 2023-07-31 at 22 08 08
Screenshot 2023-07-31 at 22 08 01
Screenshot 2023-07-31 at 22 07 26
Screenshot 2023-07-31 at 22 07 21

### CODE REVIEW

**Comment by bexsoft** [comment]
> @bexsoft When versioning exclusion is applied on a locking bucket, it errors out. I think it should not be functional for locking enabled bucket.
> 
> ```json
> {
>     "code": 500,
>     "detailedMessage": "error setting versioning for bucket: An Object Lock configuration is present on this bucket, versioning cannot be suspended.",
>     "message": "an error occurred, please try again"
> }
> ```
> 
> Input.

Added extra validations to avoid this behavior

**Review by prakashsvmx — APPROVED** [review]
Tested. LGTM :+1:

**Review by cniackz — APPROVED** [review]

**Comment by cniackz** [comment]
Test `Integration Tests with Latest Distributed MinIO` will pass when MinIO gets these API changes. If it does not, I will be updating our test to match with new API changes. But for now the suggestion is to merge this PR and let the code be included under minio repo.

**Comment by bexsoft** [comment]
For the missing Integration test, this change must be integrated in MinIO server in order to get it passing (This is related to a change in versioning API that is not present yet in MinIO server). 

We will be monitoring this once a new Console release is made.

**Pull request merged**
