### PR TITLE
[Blocked] Added upgrade page to console

### PR DESCRIPTION
**Pull request by bexsoft**

### CODE REVIEW

**Comment by dvaldivia** [comment]
can you rebase this @bexsoft ?

**Comment by bexsoft** [comment]
> @bexsoft Going to create a new branch for this so i can commit new changes, will keep this one for reference until i have ready the other one

You can create a PR to my branch, Will give you write access to it

**Comment by cesnietor** [comment]
@bexsoft  can we close this one? or is still in progress?

**Comment by bexsoft** [comment]
> @bexsoft can we close this one? or is still in progress?

No, Waiting on approval, need to discuss with Daniel & Jaview

**Comment by bexsoft** [comment]
This feature will not be implemented at this moment. We can close and reopen in case of necessary

**Pull request closed without merging**
