### PR TITLE
Customization of Dashboard page & improved some styles

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

- Customized Dashboard page with new styles & icons
- Improved some missing styles in console

## How does it look?

Screen Shot 2020-10-05 at 8 58 31 PM

### CODE REVIEW

**Review by dvaldivia — APPROVED** [review]

**Comment by cesnietor** [comment]
It looks good. I had to do `make assets`, probably we should send it already with those files updated.

**Comment by cesnietor** [comment]
Also I saw for objects the header gets lost, it might be because of the way it is being redirected right now.
Screen Shot 2020-10-05 at 7 16 18 PM

**Comment by bexsoft** [comment]
> Also I saw for objects the header gets lost, it might be because of the way it is being redirected right now.
> Screen Shot 2020-10-05 at 7 16 18 PM

Fixed header & updated assets

**Review by cesnietor — APPROVED** [review]

**Review by cesnietor — APPROVED** [review]

**Review by Alevsk — APPROVED** [review]
LGTM

**Pull request merged**
